#!/bin/bash

KEYWORDS_ENGLAND="England|British" #Since most people don't know the difference between British and English
KEYWORDS_LONDON="London"
KEYWORDS_BUCKINGHAMPALACE="Buckingham(| )Palace"
KEYWORDS_ELIZABETHTOWER="Elizabeth(| )Tower"
KEYWORDS_TOWEROFLONDON="Tower(| )of(| )London"
KEYWORDS_LONDON_EXCLUDE="Jack(| )London|$KEYWORDS_BUCKINGHAMPALACE|$KEYWORDS_ELIZABETHTOWER|$KEYWORDS_TOWEROFLONDON" #Jack London was an American author
KEYWORDS_LONDON_ALL="$KEYWORDS_LONDON|$KEYWORDS_BUCKINGHAMPALACE|$KEYWORDS_ELIZABETHTOWER|$KEYWORDS_TOWEROFLONDON"
KEYWORDS_STONEHENGE="Stonehenge"
KEYWORDS_ENGLAND_EXCLUDE="$KEYWORDS_LONDON_ALL|$KEYWORDS_STONEHENGE|British(| )Columbia|New(| )England|Church(| )of(| )England|British(| )Isles"
KEYWORDS_ENGLAND_ALL="$KEYWORDS_ENGLAND|$KEYWORDS_LONDON_ALL|$KEYWORDS_STONEHENGE"

if [ "$1" == "" ];
then

  debug_start "England"

  ENGLAND=$(egrep -i "$KEYWORDS_ENGLAND" "$NEWPAGES" | egrep -iv "$KEYWORDS_ENGLAND_EXCLUDE")
  LONDON=$(egrep -i "$KEYWORDS_LONDON" "$NEWPAGES" | egrep -iv "$KEYWORDS_LONDON_EXCLUDE")
  BUCKINGHAMPALACE=$(egrep -i "$KEYWORDS_BUCKINGHAMPALACE" "$NEWPAGES")
  ELIZABETHTOWER=$(egrep -i "$KEYWORDS_ELIZABETHTOWER" "$NEWPAGES")
  TOWEROFLONDON=$(egrep -i "$KEYWORDS_TOWEROFLONDON" "$NEWPAGES")
  STONEHENGE=$(egrep -i "$KEYWORDS_STONEHENGE" "$NEWPAGES")

  categorize "ENGLAND" "England"
  categorize "LONDON" "London"
  categorize "BUCKINGHAMPALACE" "Buckingham Palace"
  categorize "ELIZABETHTOWER" "Elizabeth Tower"
  categorize "TOWEROFLONDON" "Tower of London"
  categorize "STONEHENGE" "Stonehenge"

  debug_end "England"

fi