#!/bin/bash

KEYWORDS_FINALFANTASY="Final(| )Fantasy"
KEYWORDS_FINALFANTASY2="$KEYWORDS_FINALFANTASY(| )(2|II\b)|\bFF(| )2\b"
KEYWORDS_FINALFANTASY3="$KEYWORDS_FINALFANTASY(| )(3|III\b)|\bFF(| )(3|III)\b"
KEYWORDS_FINALFANTASY4="$KEYWORDS_FINALFANTASY(| )(4|IV\b)|\bFF(| )(IV|4)\b"
KEYWORDS_FINALFANTASY5="$KEYWORDS_FINALFANTASY(| )(5|V\b)|\bFF(| )(V|5)\b"
KEYWORDS_FINALFANTASY6="$KEYWORDS_FINALFANTASY(| )(6|VI\b)|\bFF(| )(VI|6)\b"
KEYWORDS_FINALFANTASY7="$KEYWORDS_FINALFANTASY(| )(7|VII\b)|\bFF(| )(VII|7)\b"
KEYWORDS_FINALFANTASY8="$KEYWORDS_FINALFANTASY(| )(8|VIII\b)|\bFF(| )(VIII|8)\b"
KEYWORDS_FINALFANTASY9="$KEYWORDS_FINALFANTASY(| )(9|IX\b)|\bFF(| )(IX|9)\b"
KEYWORDS_FINALFANTASYX="$KEYWORDS_FINALFANTASY(| )(10|X\b)|\bFF(| )(X|10)\b|blitzball"
KEYWORDS_FINALFANTASYX2="$KEYWORDS_FINALFANTASY(| )X-2|\bFF(| )X(|-| )2"
KEYWORDS_FINALFANTASY11="$KEYWORDS_FINALFANTASY(| )(11|XI\b)|\bFF(| )(XI|11)\b"
KEYWORDS_FINALFANTASY12="$KEYWORDS_FINALFANTASY(| )(12|XII\b)|\bFF(| )(XII|12)\b"
KEYWORDS_FINALFANTASY13="$KEYWORDS_FINALFANTASY(| )(13|XIII\b)|\bFF(| )(XIII|13)\b"
KEYWORDS_ADVENTCHILDREN="Advent(| )Children"


KEYWORDS_FINALFANTASY7_EXCLUDE="Before(| )Crisis|Crisis(| )Core|Dirge(| )of(| )Cerberus|$KEYWORDS_ADVENTCHILDREN"
KEYWORDS_FINALFANTASYX_EXCLUDE="$KEYWORDS_FINALFANTASYX2"
KEYWORDS_FINALFANTASY_EXCLUDE="$KEYWORDS_FINALFANTASY2|$KEYWORDS_FINALFANTASY3|$KEYWORDS_FINALFANTASY4|$KEYWORDS_FINALFANTASY5|$KEYWORDS_FINALFANTASY6|$KEYWORDS_FINALFANTASY6|$KEYWORDS_FINALFANTASY7|$KEYWORDS_FINALFANTASY8|$KEYWORDS_FINALFANTASY9|$KEYWORDS_FINALFANTASYX|$KEYWORDS_FINALFANTASYX2|$KEYWORDS_FINALFANTASY11|$KEYWORDS_FINALFANTASY12|$KEYWORDS_FINALFANTASY13"

if [ "$1" == "" ]; #Normal run
then

  debug_start "Final Fantasy series"

  FFSERIES=$(egrep -i "$KEYWORDS_FINALFANTASY" "$NEWPAGES" | egrep -iv "$KEYWORDS_FINALFANTASY_EXCLUDE")
  FF2=$(egrep -i "$KEYWORDS_FINALFANTASY2" "$NEWPAGES")
  FF3=$(egrep -i "$KEYWORDS_FINALFANTASY3" "$NEWPAGES")
  FF4=$(egrep -i "$KEYWORDS_FINALFANTASY4" "$NEWPAGES")
  FF5=$(egrep -i "$KEYWORDS_FINALFANTASY5" "$NEWPAGES")
  FF6=$(egrep -i "$KEYWORDS_FINALFANTASY6" "$NEWPAGES")
  FF7=$(egrep -i "$KEYWORDS_FINALFANTASY7" "$NEWPAGES" | egrep -iv "$KEYWORDS_FINALFANTASY7_EXCLUDE")
  FF8=$(egrep -i "$KEYWORDS_FINALFANTASY8" "$NEWPAGES")
  FF9=$(egrep -i "$KEYWORDS_FINALFANTASY9" "$NEWPAGES")
  FF10=$(egrep -i "$KEYWORDS_FINALFANTASYX" "$NEWPAGES" | egrep -iv "$KEYWORDS_FINALFANTASYX_EXCLUDE")
  FFX2=$(egrep -i "$KEYWORDS_FINALFANTASYX2" "$NEWPAGES")
  FF11=$(egrep -i "$KEYWORDS_FINALFANTASY11" "$NEWPAGES")
  FF12=$(egrep -i "$KEYWORDS_FINALFANTASY12" "$NEWPAGES")
  FF13=$(egrep -i "$KEYWORDS_FINALFANTASY13" "$NEWPAGES")
  ADVENT=$(egrep -i "$KEYWORDS_ADVENTCHILDREN" "$NEWPAGES")

  categorize "FFSERIES" "Final Fantasy series"
  categorize "FF2" "Final Fantasy II"
  categorize "FF3" "Final Fantasy III"
  categorize "FF4" "Final Fantasy IV"
  categorize "FF5" "Final Fantasy V"
  categorize "FF6" "Final Fantasy VI"
  categorize "FF7" "Final Fantasy VII"
  categorize "FF8" "Final Fantasy VIII"
  categorize "FF9" "Final Fantasy IX"
  categorize "FF10" "Final Fantasy X"
  categorize "FFX2" "Final Fantasy X-2"
  categorize "FF11" "Final Fantasy XI"
  categorize "FF12" "Final Fantasy XII"
  categorize "FF13" "Final Fantasy XIII"
  categorize "ADVENT" "Final Fantasy VII: Advent Children"

  debug_end "Final Fantasy series"

fi