#!/bin/bash

KEYWORDS_GABITE="Gabite"
KEYWORDS_GALLADE="Gallade"
KEYWORDS_GALVANTULA="Galvantula"
KEYWORDS_GARBODOR="Garbodor"
KEYWORDS_GARCHOMP="Garchomp"
KEYWORDS_GARDEVOIR="Gardevoir"
KEYWORDS_GASTLY="Gastly"
KEYWORDS_GASTRODON="Gastrodon"
KEYWORDS_GENESECT="Genesect"
KEYWORDS_GENGAR="Gengar"
KEYWORDS_GEODUDE="Geodude"
KEYWORDS_GIBLE="\bGible"
KEYWORDS_GIGALITH="Gigalith"
KEYWORDS_GIRAFARIG="Girafarig"
KEYWORDS_GIRATINA="Giratina"
KEYWORDS_GLACEON="Glaceon"
KEYWORDS_GLALIE="Glalie"
KEYWORDS_GLAMEOW="Glameow"
KEYWORDS_GLIGAR="Gligar"
KEYWORDS_GLISCOR="Gliscor"
KEYWORDS_GLOOM="Gloom\b"
KEYWORDS_GOLBAT="Golbat"
KEYWORDS_GOLDEEN="Goldeen"
KEYWORDS_GOLDUCK="Golduck"
KEYWORDS_GOLEM="Golem"
KEYWORDS_GOLETT="Golett"
KEYWORDS_GOLURK="Golurk"
KEYWORDS_GOREBYSS="Gorebyss"
KEYWORDS_GOTHITA="Gothita"
KEYWORDS_GOTHITELLE="Gothitelle"
KEYWORDS_GOTHORITA="Gothorita"
KEYWORDS_GRANBULL="Granbull"
KEYWORDS_GRAVELER="Graveler"
KEYWORDS_GRIMER="Grimer"
KEYWORDS_GROTLE="Grotle"
KEYWORDS_GROUDON="Groudon"
KEYWORDS_GROVYLE="Grovyle"
KEYWORDS_GROWLITHE="Growlithe"
KEYWORDS_GRUMPIG="Grumpig"
KEYWORDS_GULPIN="Gulpin"
KEYWORDS_GURDURR="Gurdurr"
KEYWORDS_GYARADOS="Gyarados"
KEYWORDS_POKEMONSPECIES_G="$KEYWORDS_GABITE|$KEYWORDS_GALLADE|$KEYWORDS_GALVANTULA|$KEYWORDS_GARBODOR|$KEYWORDS_GARCHOMP|$KEYWORDS_GARDEVOIR|$KEYWORDS_GASTLY|$KEYWORDS_GASTRODON|$KEYWORDS_GENESECT|$KEYWORDS_GENGAR|$KEYWORDS_GEODUDE|$KEYWORDS_GIBLE|$KEYWORDS_GIGALITH|$KEYWORDS_GIRAFARIG|$KEYWORDS_GIRATINA|$KEYWORDS_GLACEON|$KEYWORDS_GLALIE|$KEYWORDS_GLAMEOW|$KEYWORDS_GLAMEOW|$KEYWORDS_GLIGAR|$KEYWORDS_GLIGAR|$KEYWORDS_GLISCOR|$KEYWORDS_GLOOM|$KEYWORDS_GOLBAT|$KEYWORDS_GOLDEEN|$KEYWORDS_GOLDUCK|$KEYWORDS_GOLEM|$KEYWORDS_GOLETT|$KEYWORDS_GOLURK|$KEYWORDS_GOREBYSS|$KEYWORDS_GOREBYSS|$KEYWORDS_GOTHITA|$KEYWORDS_GOTHITELLE|$KEYWORDS_GOTHORITA|$KEYWORDS_GRANBULL|$KEYWORDS_GRAVELER|$KEYWORDS_GRIMER|$KEYWORDS_GROTLE|$KEYWORDS_GROUDON|$KEYWORDS_GROVYLE|$KEYWORDS_GROWLITHE|$KEYWORDS_GRUMPIG|$KEYWORDS_GULPIN|$KEYWORDS_GURDURR|$KEYWORDS_GYARADOS"


if [ "$1" == "" ]; #Normal operation
then

  debug_start "Pokemon G script"

  GABITE=$(egrep -i "$KEYWORDS_GABITE" "$NEWPAGES")
  GALLADE=$(egrep -i "$KEYWORDS_GALLADE" "$NEWPAGES")
  GARBODOR=$(egrep -i "$KEYWORDS_GARBODOR" "$NEWPAGES")
  GARCHOMP=$(egrep -i "$KEYWORDS_GARCHOMP" "$NEWPAGES")
  GARDEVOIR=$(egrep -i "$KEYWORDS_GARDEVOIR" "$NEWPAGES")
  GASTLY=$(egrep -i "$KEYWORDS_GASTLY" "$NEWPAGES")
  GASTRODON=$(egrep -i "$KEYWORDS_GASTRODON" "$NEWPAGES")
  GALVANTULA=$(egrep -i "$KEYWORDS_GALVANTULA" "$NEWPAGES")
  GENESECT=$(egrep -i "$KEYWORDS_GENESECT" "$NEWPAGES")
  GENGAR=$(egrep -i "$KEYWORDS_GENGAR" "$NEWPAGES")
  GEODUDE=$(egrep -i "$KEYWORDS_GEODUDE" "$NEWPAGES")
  GIBLE=$(egrep -i "$KEYWORDS_GIBLE" "$NEWPAGES")
  GIGALITH=$(egrep -i "$KEYWORDS_GIGALITH" "$NEWPAGES")
  GIRAFARIG=$(egrep -i "$KEYWORDS_GIRAFARIG" "$NEWPAGES")
  GIRATINA=$(egrep -i "$KEYWORDS_GIRATINA" "$NEWPAGES")
  GLACEON=$(egrep -i "$KEYWORDS_GLACEON" "$NEWPAGES")
  GLALIE=$(egrep -i "$KEYWORDS_GLALIE" "$NEWPAGES")
  GLAMEOW=$(egrep -i "$KEYWORDS_GLAMEOW" "$NEWPAGES")
  GLIGAR=$(egrep -i "$KEYWORDS_GLIGAR" "$NEWPAGES")
  GLISCOR=$(egrep -i "$KEYWORDS_GLISCOR" "$NEWPAGES")
  GLOOM=$(egrep -i "$KEYWORDS_GLOOM" "$NEWPAGES")
  GOLBAT=$(egrep -i "$KEYWORDS_GOLBAT" "$NEWPAGES")
  GOLDEEN=$(egrep -i "$KEYWORDS_GOLDEEN" "$NEWPAGES")
  GOLDUCK=$(egrep -i "$KEYWORDS_GOLDUCK" "$NEWPAGES")
  GOLEM=$(egrep -i "$KEYWORDS_GOLEM" "$NEWPAGES")
  GOLETT=$(egrep -i "$KEYWORDS_GOLETT" "$NEWPAGES")
  GOLURK=$(egrep -i "$KEYWORDS_GOLURK" "$NEWPAGES")
  GOREBYSS=$(egrep -i "$KEYWORDS_GOREBYSS" "$NEWPAGES")
  GOTHITA=$(egrep -i "$KEYWORDS_GOTHITA" "$NEWPAGES")
  GOTHITELLE=$(egrep -i "$KEYWORDS_GOTHITELLE" "$NEWPAGES")
  GOTHORITA=$(egrep -i "$KEYWORDS_GOTHORITA" "$NEWPAGES")
  GRANBULL=$(egrep -i "$KEYWORDS_GRANBULL" "$NEWPAGES")
  GRAVELER=$(egrep -i "$KEYWORDS_GRAVELER" "$NEWPAGES")
  GRIMER=$(egrep -i "$KEYWORDS_GRIMER" "$NEWPAGES")
  GROTLE=$(egrep -i "$KEYWORDS_GROTLE" "$NEWPAGES")
  GROUDON=$(egrep -i "$KEYWORDS_GROUDON" "$NEWPAGES")
  GROVYLE=$(egrep -i "$KEYWORDS_GROVYLE" "$NEWPAGES")
  GROWLITHE=$(egrep -i "$KEYWORDS_GROWLITHE" "$NEWPAGES")
  GRUMPIG=$(egrep -i "$KEYWORDS_GRUMPIG" "$NEWPAGES")
  GULPIN=$(egrep -i "$KEYWORDS_GULPIN" "$NEWPAGES")
  GURDURR=$(egrep -i "$KEYWORDS_GURDURR" "$NEWPAGES")
  GYARADOS=$(egrep -i "$KEYWORDS_GYARADOS" "$NEWPAGES")

  categorize "GABITE" "Gabite"
  categorize "GALLADE" "Gallade"
  categorize "GARBODOR" "Garbodor"
  categorize "GARCHOMP" "Garchomp"
  categorize "GARDEVOIR" "Gardevoir"
  categorize "GASTLY" "Gastly"
  categorize "GASTRODON" "Gastrodon"
  categorize "GALVANTULA" "Galvantula"
  categorize "GENESECT" "Genesect"
  categorize "GENGAR" "Gengar"
  categorize "GEODUDE" "Geodude"
  categorize "GIBLE" "Gible"
  categorize "GIGALITH" "Gigalith"
  categorize "GIRAFARIG" "Girafarig"
  categorize "GIRATINA" "Giratina"
  categorize "GLACEON" "Glaceon"
  categorize "GLALIE" "Glalie"
  categorize "GLAMEOW" "Glameow"
  categorize "GLIGAR" "Gligar"
  categorize "GLISCOR" "Gliscor"
  categorize "GLOOM" "Gloom"
  categorize "GOLBAT" "Golbat"
  categorize "GOLDEEN" "Goldeen"
  categorize "GOLDUCK" "Golduck"
  categorize "GOLEM" "Golem"
  categorize "GOLETT" "Golett"
  categorize "GOLURK" "Golurk"
  categorize "GOREBYSS" "Gorebyss"
  categorize "GOTHITA" "Gothita"
  categorize "GOTHITELLE" "Gothitelle"
  categorize "GOTHORITA" "Gothorita"
  categorize "GRANBULL" "Granbull"
  categorize "GRAVELER" "Graveler (Pokémon)"
  categorize "GRIMER" "Grimer"
  categorize "GROTLE" "Grotle"
  categorize "GROUDON" "Groudon"
  categorize "GROVYLE" "Grovyle"
  categorize "GROWLITHE" "Growlithe"
  categorize "GRUMPIG" "Grumpig"
  categorize "GULPIN" "Gulpin"
  categorize "GURDURR" "Gurdurr"
  categorize "GYARADOS" "Gyarados"


  debug_end "Pokemon G script"

fi