#!/bin/bash

KEYWORDS_EELEKTRIK="Eelektrik"
KEYWORDS_EELEKTROSS="Eelektross"
KEYWORDS_EEVEE="Eevee"
KEYWORDS_EKANS="Ekans"
KEYWORDS_ELECTABUZZ="Electabuzz"
KEYWORDS_ELECTIVIRE="Electivire"
KEYWORDS_ELECTRIKE="Electrike"
KEYWORDS_ELECTRODE="Electrode"
KEYWORDS_ELEKID="Elekid"
KEYWORDS_ELGYEM="Elgyem"
KEYWORDS_EMBOAR="Emboar"
KEYWORDS_EMOLGA="Emolga"
KEYWORDS_EMPOLEON="Empoleon"
KEYWORDS_ENTEI="Entei"
KEYWORDS_ESCAVALIER="Escavalier"
KEYWORDS_ESPEON="Espeon"
KEYWORDS_ESPURR="Espurr"
KEYWORDS_EXCADRILL="Excadrill"
KEYWORDS_EXEGGCUTE="Exeggcute"
KEYWORDS_EXEGGUTOR="Exeggutor"
KEYWORDS_EXPLOUD="Exploud"
KEYWORDS_POKEMONSPECIES_E="$KEYWORDS_EELEKTRIK|$KEYWORDS_EELEKTROSS|$KEYWORDS_EEVEE|$KEYWORDS_EKANS|$KEYWORDS_ELECTABUZZ|$KEYWORDS_ELECTIVIRE|$KEYWORDS_ELECTRIKE|$KEYWORDS_ELECTRODE|$KEYWORDS_ELEKID|$KEYWORDS_ELGYEM|$KEYWORDS_EMBOAR|$KEYWORDS_EMOLGA|$KEYWORDS_EMPOLEON|$KEYWORDS_ENTEI|$KEYWORDS_ESCAVALIER|$KEYWORDS_ESPEON|$KEYWORDS_ESPURR|$KEYWORDS_EXCADRILL|$KEYWORDS_EXEGGCUTE|$KEYWORDS_EXEGGUTOR|$KEYWORDS_EXPLOUD"


if [ "$1" == "" ]; #Normal operation
then

  debug_start "Pokemon species E"

  EELEKTRIK=$(egrep -i "$KEYWORDS_EELEKTRIK" "$NEWPAGES")
  EELEKTROSS=$(egrep -i "$KEYWORDS_EELEKTROSS" "$NEWPAGES")
  EEVEE=$(egrep -i "$KEYWORDS_EEVEE" "$NEWPAGES")
  EKANS=$(egrep -i "$KEYWORDS_EKANS" "$NEWPAGES")
  ELECTABUZZ=$(egrep -i "$KEYWORDS_ELECTABUZZ" "$NEWPAGES")
  ELECTIVIRE=$(egrep -i "$KEYWORDS_ELECTIVIRE" "$NEWPAGES")
  ELECTRIKE=$(egrep -i "$KEYWORDS_ELECTRIKE" "$NEWPAGES")
  ELECTRODE=$(egrep -i "$KEYWORDS_ELECTRODE" "$NEWPAGES")
  ELEKID=$(egrep -i "$KEYWORDS_ELEKID" "$NEWPAGES")
  ELGYEM=$(egrep -i "$KEYWORDS_ELGYEM" "$NEWPAGES")
  EMBOAR=$(egrep -i "$KEYWORDS_EMBOAR" "$NEWPAGES")
  EMOLGA=$(egrep -i "$KEYWORDS_EMOLGA" "$NEWPAGES")
  EMPOLEON=$(egrep -i "$KEYWORDS_EMPOLEON" "$NEWPAGES")
  ENTEI=$(egrep -i "$KEYWORDS_ENTEI" "$NEWPAGES")
  ESCAVALIER=$(egrep -i "$KEYWORDS_ESCAVALIER" "$NEWPAGES")
  ESPEON=$(egrep -i "$KEYWORDS_ESPEON" "$NEWPAGES")
  ESPURR=$(egrep -i "$KEYWORDS_ESPURR" "$NEWPAGES")
  EXCADRILL=$(egrep -i "$KEYWORDS_EXCADRILL" "$NEWPAGES")
  EXEGGCUTE=$(egrep -i "$KEYWORDS_EXEGGCUTE" "$NEWPAGES")
  EXEGGUTOR=$(egrep -i "$KEYWORDS_EXEGGUTOR" "$NEWPAGES")
  EXPLOUD=$(egrep -i "$KEYWORDS_EXPLOUD" "$NEWPAGES")

  categorize "EELEKTRIK" "Eelektrik"
  categorize "EELEKTROSS" "Eelektross"
  categorize "EEVEE" "Eevee"
  categorize "EKANS" "Ekans"
  categorize "ELECTABUZZ" "Electabuzz"
  categorize "ELECTIVIRE" "Electivire"
  categorize "ELECTRIKE" "Electrike"
  categorize "ELECTRODE" "Electrode"
  categorize "ELEKID" "Elekid"
  categorize "ELGYEM" "Elgyem"
  categorize "EMBOAR" "Emboar"
  categorize "EMOLGA" "Emolga"
  categorize "EMPOLEON" "Empoleon"
  categorize "ENTEI" "Entei"
  categorize "ESCAVALIER" "Escavalier"
  categorize "ESPEON" "Espeon"
  categorize "ESPURR" "Espurr"
  categorize "EXCADRILL" "Excadrill"
  categorize "EXEGGCUTE" "Exeggcute"
  categorize "EXEGGUTOR" "Exeggutor"
  categorize "EXPLOUD" "Exploud"

  debug_end "Pokemon species E"

fi