#!/bin/bash

KEYWORDS_REPTILES="Reptile"

KEYWORDS_TURTLES="Turtle|Tortoise|Terrapin"
KEYWORDS_TURTLES_EXCLUDE="tenneage|mutant|ninja|TMNT|Turtle(| )Knock"
KEYWORDS_TURTLES_ALL="$KEYWORDS_TURTLES"

KEYWORDS_SNAKES="Snake"
KEYWORDS_PYTHONS="python"
KEYWORDS_PYTHONS_EXCLUDE="in python\b|program|script|computer(| )language|Metal(| )Gear|Monty(| )Python"
KEYWORDS_RATTLESNAKES="Rattle(| )snake"
KEYWORDS_BOA="\bBoa(|s)\b"
KEYWORDS_BOAS_EXCLUDE="$KEYWORDS_ANACONDAS|Boa(| )Hancock"
KEYWORDS_ANACONDAS="Anaconda"
KEYWORDS_COBRAS="Cobra"
KEYWORDS_COBRAS_EXCLUDE="Cobra(| )Commando|Shelby(| )Cobra|G(\.|)I(\.|)(| )Joe|Mustang"
KEYWORDS_SNAKES_EXCLUDE="Solid(| )Snake|$KEYWORDS_PYTHONS|Metal(| )Gear|$KEYWORDS_RATTLESNAKES|$KEYWORDS_BOA|$KEYWORDS_ANACONDAS|$KEYWORDS_COBRAS"
KEYWORDS_SNAKES_ALL="$KEYWORDS_SNAKES|$KEYWORDS_PYTHONS|$KEYWORDS_ANACONDAS|$KEYWORDS_RATTLESNAKES|$KEYWORDS_BOA|$KEYWORDS_COBRAS"

KEYWORDS_LIZARDS="Lizard|komodo(| )dragon"
KEYWORDS_IGUANAS="Iguana"
KEYWORDS_BEARDEDDRAGONS="Bearded(| )dragon"
KEYWORDS_GECKOS="Gecko"
KEYWORDS_SKINKS="Skink"
KEYWORDS_LIZARDS_EXCLUDE="$KEYWORDS_IGUANAS|$KEYWORDS_BEARDEDDRAGONS|$KEYWORDS_GECKOS|$KEYWORDS_SKINKS"
KEYWORDS_LIZARDS_ALL="$KEYWORDS_LIZARDS|$KEYWORDS_IGUANAS|$KEYWORDS_BEARDEDDRAGONS|$KEYWORDS_GECKOS|$KEYWORDS_SKINKS"

KEYWORDS_CROCODILES="Crocodile"
KEYWORDS_ALLIGATORS="Alligator|Caiman"
KEYWORDS_CROCODILES_EXCLUDE="Crocodile(| )Dundee|Crocodile(| )Hunter"

KEYWORDS_TUATARA="Tuatara"
KEYWORDS_TUATARA_ALL="$KEYWORDS_TUATARA"

KEYWORDS_REPTILES_EXCLUDE="$KEYWORDS_TURTLES_ALL|$KEYWORDS_SNAKES_ALL|$KEYWORDS_LIZARDS_ALL|$KEYWORDS_TUATARA_ALL|$KEYWORDS_ALLIGATORS|$KEYWORDS_CROCODILES"

KEYWORDS_REPTILES_ALL="$KEYWORDS_REPTILES|$KEYWORDS_TURTLES_ALL|$KEYWORDS_SNAKES_ALL|$KEYWORDS_CROCODILES|$KEYWORDS_ALLIGATORS|$KEYWORDS_LIZARDS_ALL|$KEYWORDS_TUATARA"

if [ "$1" == "" ];
then

  debug_start "Reptiles"

  REPTILES=$(egrep -i "$KEYWORDS_REPTILES" "$NEWPAGES" | egrep -iv "$KEYWORDS_REPTILES_EXCLUDE")
  TURTLES=$(egrep -i "$KEYWORDS_TURTLES" "$NEWPAGES" | egrep -iv "$KEYWORDS_TURTLES_EXCLUDE")
  SNAKES=$(egrep -i "$KEYWORDS_SNAKES" "$NEWPAGES" | egrep -iv "$KEYWORDS_SNAKES_EXCLUDE")
  LIZARDS=$(egrep -i "$KEYWORDS_LIZARDS" "$NEWPAGES" | egrep -iv "$KEYWORDS_LIZARDS_EXCLUDE")
  CROCODILES=$(egrep -i "$KEYWORDS_CROCODILES" "$NEWPAGES" | egrep -iv "$KEYWORDS_CROCODILES_EXCLUDE")
  ALLIGATORS=$(egrep -i "$KEYWORDS_ALLIGATORS" "$NEWPAGES")
  TUATARA=$(egrep -i "$KEYWORDS_TUATARA" "$NEWPAGES")
  IGUANAS=$(egrep -i "$KEYWORDS_IGUANAS" "$NEWPAGES")
  BEARDEDDRAGON=$(egrep -i "$KEYWORDS_BEARDEDDRAGONS" "$NEWPAGES")
  GECKOS=$(egrep -i "$KEYWORDS_GECKOS" "$NEWPAGES")
  SKINKS=$(egrep -i "$KEYWORDS_SKINKS" "$NEWPAGES")
  PYTHONS=$(egrep -i "$KEYWORDS_PYTHONS" "$NEWPAGES" | egrep -iv "$KEYWORDS_PYTHONS_EXCLUDE")
  RATTLESNAKES=$(egrep -i "$KEYWORDS_RATTLESNAKES" "$NEWPAGES")
  BOA=$(egrep -i "$KEYWORDS_BOA" "$NEWPAGES" | egrep -iv "$KEYWORDS_BOA_EXCLUDE")
  ANACONDAS=$(egrep -i "$KEYWORDS_ANACONDAS" "$NEWPAGES")
  COBRAS=$(egrep -i "$KEYWORDS_COBRAS" "$NEWPAGES" | egrep -iv "$KEYWORDS_COBRAS_EXCLUDE")

  categorize "REPTILES" "Reptiles"
  categorize "TURTLES" "Turtles"
  categorize "SNAKES" "Snakes"
  categorize "LIZARDS" "Lizards"
  categorize "CROCODILES" "Crocodiles"
  categorize "ALLIGATORS" "Alligators"
  categorize "TUATARA" "Tuatara"
  categorize "BEARDEDDRAGON" "Bearded dragons"
  categorize "IGUANAS" "Iguanas"
  categorize "GECKOS" "Geckos"
  categorize "SKINKS" "Skinks"
  categorize "PYTHONS" "Pythons"
  categorize "RATTLESNAKES" "Rattlesnakes"
  categorize "BOA" "Boa"
  categorize "ANACONDAS" "Anacondas"
  categorize "COBRAS" "Cobras"

  debug_end "Reptiles"

fi