#!/bin/bash

SOCIALNETWORKDIR="./catscripts/Technology/Computers/Internet/Websites/Social_networking"
KEYWORDS_SOCIALNETWORKING="Social(| )network|social(| )media"

if [ "$1" == "" ];
then

  debug_start "Social networking websites"

  . $SOCIALNETWORKDIR/Facebook.sh #KEYWORDS_FACEBOOK
  . $SOCIALNETWORKDIR/GaiaOnline.sh #KEYWORDS_GAIAONLINE
  . $SOCIALNETWORKDIR/Myspace.sh #KEYWORDS_MYSPACE
  . $SOCIALNETWORKDIR/Twitter.sh #KEYWORDS_TWITTER
  . $SOCIALNETWORKDIR/Tumblr.sh #KEYWORDS_TUMBLR
  . $SOCIALNETWORKDIR/Woozworld.sh #KEYWORDS_WOOZWORLD


  KEYWORDS_SOCIALNETWORKING_EXCLUDE="$KEYWORDS_FACEBOOK|$KEYWORDS_GAIAONLINE|$KEYWORDS_MYSPACE|$KEYWORDS_TWITTER|$KEYWORDS_WOOZWORLD|$KEYWORDS_TUMBLR"
  KEYWORDS_SOCIALNETWORKING_ALL="$KEYWORDS_SOCIALNETWORKING|$KEYWORDS_FACEBOOK|$KEYWORDS_GAIAONLINE|$KEYWORDS_MYSPACE|$KEYWORDS_TUMBLR|$KEYWORDS_TWITTER|$KEYWORDS_WOOZWORLD"

  SOCIALNETWORK=$(egrep -i "$KEYWORDS_SOCIALNETWORKING" "$NEWPAGES" | egrep -iv "$KEYWORDS_SOCIALNETWORKING_EXCLUDE")

  categorize "SOCIALNETWORK" "Social networking websites"

  debug_end "Social networking websites"

else

  . $SOCIALNETWORKDIR/Facebook.sh norun #KEYWORDS_FACEBOOK
  . $SOCIALNETWORKDIR/GaiaOnline.sh norun #KEYWORDS_GAIAONLINE
  . $SOCIALNETWORKDIR/Myspace.sh norun #KEYWORDS_MYSPACE
  . $SOCIALNETWORKDIR/Twitter.sh norun #KEYWORDS_TWITTER
  . $SOCIALNETWORKDIR/Tumblr.sh norun #KEYWORDS_TUMBLR
  . $SOCIALNETWORKDIR/Woozworld.sh norun #KEYWORDS_WOOZWORLD

  KEYWORDS_SOCIALNETWORKING_ALL="$KEYWORDS_SOCIALNETWORKING|$KEYWORDS_FACEBOOK|$KEYWORDS_GAIAONLINE|$KEYWORDS_MYSPACE|$KEYWORDS_TUMBLR|$KEYWORDS_TWITTER|$KEYWORDS_WOOZWORLD"

fi

#This is to stop ShellCheck from complaining about KEYWORDS_SOCIALNETWORKING_ALL, which is used elsewhere

KEYWORDS_SOCIALNETWORKING_ALL="$KEYWORDS_SOCIALNETWORKING_ALL"