#!/bin/bash

APOLLODIR="$NASADIR/Apollo_missions"

KEYWORDS_APOLLOMISSIONS="Apollo(| )(missions|moon(| )landing)|Apollo(| )[0-9]{1,}"

if [ "$1" == "" ];
then
  
  debug_start "Apollo missions"

  . "$APOLLODIR/Apollo_11/Apollo11.sh" #KEYWORDS_APOLLO11_ALL
  . "$APOLLODIR/Apollo_13/Apollo13.sh" #KEYWORDS_APOLLO13_ALL

  KEYWORDS_APOLLOMISSIONS_EXCLUDE="$KEYWORDS_APOLLO11_ALL|$KEYWORDS_APOLLO13_ALL"

  KEYWORDS_APOLLOMISSIONS_ALL="$KEYWORDS_APOLLOMISSIONS|$KEYWORDS_APOLLO11_ALL|$KEYWORDS_APOLLO13_ALL"

  APOLLOMISSIONS=$(egrep -i "$KEYWORDS_APOLLOMISSIONS" "$NEWPAGES" | egrep -iv "$KEYWORDS_APOLLOMISSIONS_EXCLUDE")

  categorize "APOLLOMISSIONS" "Apollo missions"

  debug_end "Apollo missions"

else

  . "$APOLLODIR/Apollo_11/Apollo11.sh" norun #KEYWORDS_APOLLO11_ALL
  . "$APOLLODIR/Apollo_13/Apollo13.sh" norun #KEYWORDS_APOLLO13_ALL

  KEYWORDS_APOLLOMISSIONS_EXCLUDE="$KEYWORDS_APOLLO11_ALL|$KEYWORDS_APOLLO13_ALL"

  KEYWORDS_APOLLOMISSIONS_ALL="$KEYWORDS_APOLLOMISSIONS|$KEYWORDS_APOLLO11_ALL|$KEYWORDS_APOLLO13_ALL"

fi