#!/bin/bash

KEYWORDS_CANADA="Canada|Canadian"

KEYWORDS_ONTARIO="Ontario"
KEYWORDS_TORONTO="Toronto"
KEYWORDS_OTTAWA="Ottawa"
KEYWORDS_ONTARIO_EXCLUDE="Lake(| )Ontario|$KEYWORDS_TORONTO|$KEYWORDS_OTTAWA"
KEYWORDS_ONTARIO_ALL="$KEYWORDS_ONTARIO|$KEYWORDS_TORONTO|$KEYWORDS_OTTAWA"

KEYWORDS_QUEBEC_PROVINCE="Quebec"
KEYWORDS_QUEBEC_CITY="Quebec(|,)(| )Quebec|Quebec(| )City|City(| )of(| )Quebec" #This is going to make my head hurt
KEYWORDS_MONTREAL="Montreal"
KEYWORDS_QUEBEC_PROVINCE_EXCLUDE="$KEYWORDS_MONTREAL|$KEYWORDS_QUEBEC_CITY"
KEYWORDS_QUEBEC_PROVINCE_ALL="$KEYWORDS_QUEBEC_PROVINCE|$KEYWORDS_QUEBEC_CITY|$KEYWORDS_MONTREAL"

KEYWORDS_NOVASCOTIA="Nova(| )Scotia"
KEYWORDS_HALIFAX="Halifax"
KEYWORDS_NOVASCOTIA_EXCLUDE="$KEYWORDS_HALIFAX"
KEYWORDS_NOVASCOTIA_ALL="$KEYWORDS_NOVASCOTIA|$KEYWORDS_HALIFAX"

KEYWORDS_NEWBRUNSWICK="New(| )Brunswick|Fredericton"
KEYWORDS_NEWBRUNSWICK_ALL="$KEYWORDS_NEWBRUNSWICK"

KEYWORDS_MANITOBA="Manitoba"
KEYWORDS_WINNIPEG="Winnipeg"
KEYWORDS_MANITOBA_EXCLUDE="$KEYWORDS_WINNIPEG"
KEYWORDS_MANITOBA_ALL="$KEYWORDS_MANITOBA|$KEYWORDS_WINNIPEG"

KEYWORDS_BRITISHCOLUMBIA="British(| )Columbia"
KEYWORDS_VICTORIABC="Victoria(|,)(| )(B(|\.)C|British(| )Columbia)"
KEYWORDS_VANCOUVER="Vancouver"
KEYWORDS_BRITISHCOLUMBIA_EXCLUDE="$KEYWORDS_VICTORIABC|$KEYWORDS_VANCOUVER"
KEYWORDS_BRITISHCOLUMBIA_ALL="$KEYWORDS_BRITISHCOLUMBIA|$KEYWORDS_VICTORIABC|$KEYWORDS_VANCOUVER"

KEYWORDS_PRINCEEDWARDISLAND="Prince(| )Edward(| )Island|Charlottetown"
KEYWORDS_PRINCEEDWARDISLAND_ALL="$KEYWORDS_PRINCEEDWARDISLAND"

KEYWORDS_SASKATCHEWAN="Saskatchewan"
KEYWORDS_REGINA="Regina\b"
KEYWORDS_REGINA_EXCLUDE="Regina(| )(Spekter|Lasko)"
KEYWORDS_SASKATOON="Saskatoon"
KEYWORDS_SASKATCHEWAN_EXCLUDE="$KEYWORDS_REGINA|$KEYWORDS_SASKATOON"
KEYWORDS_SASKATCHEWAN_ALL="$KEYWORDS_SASKATCHEWAN|$KEYWORDS_REGINA|$KEYWORDS_SASKATOON"

KEYWORDS_ALBERTA="Alberta"
KEYWORDS_EDMONTON="Edmonton"
KEYWORDS_CALGARY="Calgary"
KEYWORDS_ALBERTA_EXCLUDE="$KEYWORDS_EDMONTON|$KEYWORDS_CALGARY"
KEYWORDS_ALBERTA_ALL="$KEYWORDS_ALBERTA|$KEYWORDS_EDMONTON|$KEYWORDS_CALGARY"

KEYWORDS_NEWFOUNDLANDANDLABRADOR="Newfoundland|Labrador"
KEYWORDS_NEWFOUNDLANDANDLABRADOR_EXCLUDE="\ba Newfoundland|\ba Labrador|dog|labradors|labrador(| )retriever|puppy|puppies"
KEYWORDS_NEWFOUNDLANDANDLABRADOR_ALL="$KEYWORDS_NEWFOUNDLANDANDLABRADOR"

KEYWORDS_NORTHWESTTERRITORIES="Northwest(| )Territories"
KEYWORDS_YELLOWKNIFE="Yellowknife"
KEYWORDS_NORTHWESTTERRITORIES_EXCLUDE="$KEYWORDS_YELLOWKNIFE"
KEYWORDS_NORTHWESTTERRITORIES_ALL="$KEYWORDS_NORTHWESTTERRITORIES|$KEYWORDS_YELLOWKNIFE"

KEYWORDS_YUKON="Yukon|Whitehorse"
KEYWORDS_YUKON_EXCLUDE="GMC(| )Yukon|[0-9]{2,}(| )Yukon|Yukon-Koyuku|Denali"
KEYWORDS_YUKON_ALL="$KEYWORDS_YUKON"

KEYWORDS_NUNAVUT="Nunavut|Iqaluit"
KEYWORDS_NUNAVUT_ALL="$KEYWORDS_NUNAVUT"

KEYWORDS_CANADA_EXCLUDE="$KEYWORDS_ALBERTA_ALL|$KEYWORDS_BRITISHCOLUMBIA_ALL|$KEYWORDS_MANITOBA_ALL|$KEYWORDS_NEWBRUNSWICK_ALL|$KEYWORDS_NEWFOUNDLANDANDLABRADOR_ALL|$KEYWORDS_NORTHWESTTERRITORIES_ALL|$KEYWORDS_NOVASCOTIA_ALL|$KEYWORDS_NUNAVUT_ALL|$KEYWORDS_ONTARIO_ALL|$KEYWORDS_PRINCEEDWARDISLAND_ALL|$KEYWORDS_QUEBEC_PROVINCE_ALL|$KEYWORDS_SASKATCHEWAN_ALL|$KEYWORDS_YUKON_ALL|ginger(| )ale"

KEYWORDS_CANADA_ALL="$KEYWORDS_CANADA|$KEYWORDS_ALBERTA_ALL|$KEYWORDS_BRITISHCOLUMBIA_ALL|$KEYWORDS_MANITOBA_ALL|$KEYWORDS_NEWBRUNSWICK_ALL|$KEYWORDS_NEWFOUNDLANDANDLABRADOR_ALL|$KEYWORDS_NORTHWESTTERRITORIES_ALL|$KEYWORDS_NOVASCOTIA_ALL|$KEYWORDS_NUNAVUT_ALL|$KEYWORDS_ONTARIO_ALL|$KEYWORDS_PRINCEEDWARDISLAND_ALL|$KEYWORDS_QUEBEC_PROVINCE_ALL|$KEYWORDS_SASKATCHEWAN_ALL|$KEYWORDS_YUKON_ALL"


if [ "$1" == "" ]; #Normal operation
then
  
  debug_start "Canada"

  CANADA=$(egrep -i "$KEYWORDS_CANADA" "$NEWPAGES" | egrep -iv "$KEYWORDS_CANADA_EXCLUDE")

  categorize "CANADA" "Canada"

  ONTARIO=$(egrep -i "$KEYWORDS_ONTARIO" "$NEWPAGES" | egrep -iv "$KEYWORDS_ONTARIO_EXCLUDE")

  categorize "ONTARIO" "Ontario province"

  TORONTO=$(egrep -i "$KEYWORDS_TORONTO" "$NEWPAGES")

  categorize "TORONTO" "Toronto"

  OTTAWA=$(egrep -i "$KEYWORDS_OTTAWA" "$NEWPAGES")

  categorize "OTTAWA" "Ottawa"

  QUEBECPROVINCE=$(egrep -i "$KEYWORDS_QUEBEC_PROVINCE" "$NEWPAGES" | egrep -iv "$KEYWORDS_QUEBEC_PROVINCE_EXCLUDE")

  categorize "QUEBECPROVINCE" "Quebec province"

  QUEBECCITY=$(egrep -i "$KEYWORDS_QUEBEC_CITY" "$NEWPAGES")

  categorize "QUEBECCITY" "Quebec City"

  MONTREAL=$(egrep -i "$KEYWORDS_MONTREAL" "$NEWPAGES")

  categorize "MONTREAL" "Montreal"

  NOVASCOTIA=$(egrep -i "$KEYWORDS_NOVASCOTIA" "$NEWPAGES" | egrep -iv "$KEYWORDS_NOVASCOTIA_EXCLUDE")

  categorize "NOVASCOTIA" "Nova Scotia"

  HALIFAX=$(egrep -i "$KEYWORDS_HALIFAX" "$NEWPAGES")

  categorize "HALIFAX" "Halifax"

  NEWBRUNSWICK=$(egrep -i "$KEYWORDS_NEWBRUNSWICK" "$NEWPAGES")

  categorize "NEWBRUNSWICK" "New Brunswick"

  MANITOBA=$(egrep -i "$KEYWORDS_MANITOBA" "$NEWPAGES" | egrep -iv "$KEYWORDS_MANITOBA_EXCLUDE")

  categorize "MANITOBA" "Manitoba"

  WINNIPEG=$(egrep -i "$KEYWORDS_WINNIPEG" "$NEWPAGES")

  categorize "WINNIPEG" "Winnipeg"

  BRITISHCOLUMBIA=$(egrep -i "$KEYWORDS_BRITISHCOLUMBIA" "$NEWPAGES" | egrep -iv "$KEYWORDS_BRITISHCOLUMBIA_EXCLUDE")

  categorize "BRITISHCOLUMBIA" "British Columbia"

  VICTORIABC=$(egrep -i "$KEYWORDS_VICTORIABC" "$NEWPAGES")

  categorize "VICTORIABC" "Victoria, British Columbia"

  VANCOUVER=$(egrep -i "$KEYWORDS_VANCOUVER" "$NEWPAGES")

  categorize "VANCOUVER" "Vancouver"

  PRINCEEDWARDISLAND=$(egrep -i "$KEYWORDS_PRINCEEDWARDISLAND" "$NEWPAGES")

  categorize "PRINCEEDWARDISLAND" "Prince Edward Island"

  SASKATCHEWAN=$(egrep -i "$KEYWORDS_SASKATCHEWAN" "$NEWPAGES" | egrep -iv "$KEYWORDS_SASKATCHEWAN_EXCLUDE")

  categorize "SASKATCHEWAN" "Saskatchewan"

  REGINA=$(egrep -i "$KEYWORDS_REGINA" "$NEWPAGES" | egrep -iv "$KEYWORDS_REGINA_EXCLUDE")

  categorize "REGINA" "Regina"

  SASKATOON=$(egrep -i "$KEYWORDS_SASKATOON" "$NEWPAGES")

  categorize "SASKATOON" "Saskatoon"

  ALBERTA=$(egrep -i "$KEYWORDS_ALBERTA" "$NEWPAGES" | egrep -iv "$KEYWORDS_ALBERTA_EXCLUDE")

  categorize "ALBERTA" "Alberta"

  EDMONTON=$(egrep -i "$KEYWORDS_EDMONTON" "$NEWPAGES")

  categorize "EDMONTON" "Edmonton"

  CALGARY=$(egrep -i "$KEYWORDS_CALGARY" "$NEWPAGES")

  categorize "CALGARY" "Calgary"

  NEWFOUNDLANDANDLABRADOR=$(egrep -i "$KEYWORDS_NEWFOUNDLANDANDLABRADOR" "$NEWPAGES" | egrep -iv "$KEYWORDS_NEWFOUNDLANDANDLABRADOR_EXCLUDE")

  categorize "NEWFOUNDLANDANDLABRADOR" "Newfoundland and Labrador"

  NORTHWESTTERRITORIES=$(egrep -i "$KEYWORDS_NORTHWESTTERRITORIES" "$NEWPAGES" | egrep -iv "$KEYWORDS_NORTHWESTTERRITORIES_EXCLUDE")

  categorize "NORTHWESTTERRITORIES" "Northwest Territories"

  YELLOWKNIFE=$(egrep -i "$KEYWORDS_YELLOWKNIFE" "$NEWPAGES")

  categorize "YELLOWKNIFE" "Yellowknife"

  YUKON=$(egrep -i "$KEYWORDS_YUKON" "$NEWPAGES" | egrep -iv "$KEYWORDS_YUKON_EXCLUDE")

  categorize "YUKON" "Yukon"

  NUNAVUT=$(egrep -i "$KEYWORDS_NUNAVUT" "$NEWPAGES")

  categorize "NUNAVUT" "Nunavut"

  debug_end "Canada"

fi