#!/bin/bash

OPERATINGSYSTEMDIR="./catscripts/Technology/Computers/Software/Operating_systems"


if [ "$1" == "" ]; #Normal operation
then

  debug_start "Operating systems"

  . $OPERATINGSYSTEMDIR/FreeBSD/FreeBSD.sh #KEYWORDS_FREEBSD
  . $OPERATINGSYSTEMDIR/Linux/Linux.sh #KEYWORDS_LINUX_ALL
  . $OPERATINGSYSTEMDIR/MS-DOS/MS-DOS.sh #KEYWORDS_MSDOS
  . $OPERATINGSYSTEMDIR/Mac_OS_X/Mac_OS_X.sh #KEYWORDS_MACOS
  . $OPERATINGSYSTEMDIR/OpenBSD/OpenBSD.sh #KEYWORDS_OPENBSD
  . $OPERATINGSYSTEMDIR/Unix/Unix.sh #KEYWORDS_UNIX_ALL
  . $OPERATINGSYSTEMDIR/Windows/Windows.sh #$KEYWORDS_WINDOWS_ALL

  KEYWORDS_OPERATINGSYSTEMS="operating(| )system|(^| )OS\b"
  KEYWORDS_OPERATINGSYSTEMS_OTHER="Net(| )BSD"
  KEYWORDS_OPERATINGSYSTEMS_EXCLUDE="$KEYWORDS_WINDOWS_ALL|$KEYWORDS_UNIX_ALL|$KEYWORDS_LINUX_ALL|$KEYWORDS_MACOS|$KEYWORDS_OPENBSD|$KEYWORDS_FREEBSD|$KEYWORDS_MSDOS"
  KEYWORDS_OPERATINGSYSTEMS_ALL="$KEYWORDS_OPERATINGSYSTEMS|$KEYWORDS_OPERATINGSYSTEMS_OTHER|$KEYWORDS_OPERATINGSYSTEMS_EXCLUDE"

  OS=$(egrep -i "$KEYWORDS_OPERATINGSYSTEMS|$KEYWORDS_OPERATINGSYSTEMS_OTHER" "$NEWPAGES" | egrep -iv "$KEYWORDS_OPERATINGSYSTEMS_EXCLUDE")

  categorize "OS" "Operating systems"

  debug_end "Operating systems"

else

  . $OPERATINGSYSTEMDIR/FreeBSD/FreeBSD.sh norun
  . $OPERATINGSYSTEMDIR/Linux/Linux.sh norun
  . $OPERATINGSYSTEMDIR/MS-DOS/MS-DOS.sh norun
  . $OPERATINGSYSTEMDIR/Mac_OS_X/Mac_OS_X.sh norun
  . $OPERATINGSYSTEMDIR/OpenBSD/OpenBSD.sh norun
  . $OPERATINGSYSTEMDIR/Unix/Unix.sh norun
  . $OPERATINGSYSTEMDIR/Windows/Windows.sh norun

  KEYWORDS_OPERATINGSYSTEMS="operating(| )system|(^| )OS\b"
  KEYWORDS_OPERATINGSYSTEMS_OTHER="Net(| )BSD"
  KEYWORDS_OPERATINGSYSTEMS_EXCLUDE="$KEYWORDS_WINDOWS_ALL|$KEYWORDS_UNIX_ALL|$KEYWORDS_LINUX_ALL|$KEYWORDS_MACOS|$KEYWORDS_OPENBSD|$KEYWORDS_FREEBSD|$KEYWORDS_MSDOS"
  KEYWORDS_OPERATINGSYSTEMS_ALL="$KEYWORDS_OPERATINGSYSTEMS|$KEYWORDS_OPERATINGSYSTEMS_OTHER|$KEYWORDS_OPERATINGSYSTEMS_EXCLUDE"

fi