#!/bin/bash

OPERATINGSYSTEMDIR="./catscripts/Technology/Computers/Software/Operating_systems"


if [ "$1" == "" ]; #Normal operation
then

  . $OPERATINGSYSTEMDIR/FreeBSD/FreeBSD.sh #KEYWORDS_FREEBSD
  . $OPERATINGSYSTEMDIR/Linux/Linux.sh #KEYWORDS_LINUX_ALL
  . $OPERATINGSYSTEMDIR/MS-DOS/MS-DOS.sh #KEYWORDS_MSDOS
  . $OPERATINGSYSTEMDIR/Mac_OS_X/Mac_OS_X.sh #KEYWORDS_MACOS
  . $OPERATINGSYSTEMDIR/OpenBSD/OpenBSD.sh #KEYWORDS_OPENBSD
  . $OPERATINGSYSTEMDIR/Unix/Unix.sh #KEYWORDS_UNIX & KEYWORDS_UNIX_SPECIAL
  . $OPERATINGSYSTEMDIR/Windows/Windows.sh #$KEYWORDS_WINDOWS_ALL

  KEYWORDS_OPERATINGSYSTEMS="operating(| )system|(^| )OS\b"
  KEYWORDS_OPERATINGSYSTEMS_OTHER="Net(| )BSD"
  KEYWORDS_OPERATINGSYSTEMS_EXCLUDE="$KEYWORDS_WINDOWS_ALL|$KEYWORDS_UNIX|$KEYWORDS_UNIX_SPECIAL|$KEYWORDS_LINUX_ALL|$KEYWORDS_MACOS|$KEYWORDS_OPENBSD|$KEYWORDS_FREEBSD|$KEYWORDS_MSDOS"
  KEYWORDS_OPERATINGSYSTEMS_ALL="$KEYWORDS_OPERATINGSYSTEMS|$KEYWORDS_OPERATINGSYSTEMS_OTHER|$KEYWORDS_OPERATINGSYSTEMS_EXCLUDE"

  egrep -i "$KEYWORDS_OPERATINGSYSTEMS|$KEYWORDS_OPERATINGSYSTEMS_OTHER" newpages.txt | egrep -iv "$KEYWORDS_OPERATINGSYSTEMS_EXCLUDE" >> OperatingSystems.txt
  egrep -i "$KEYWORDS_MSDOS" newpages.txt >> MS-DOS.txt

  OS=`stat --print=%s OperatingSystems.txt`

  if [ $OS -ne 0 ];
  then
    export CATFILE="OperatingSystems.txt"
    export CATNAME="Operating systems"
    $CATEGORIZE
  fi

  rm OperatingSystems.txt

fi

if [ "$1" == "norrun" ];
then
  . $OPERATINGSYSTEMDIR/FreeBSD/FreeBSD.sh norrun
  . $OPERATINGSYSTEMDIR/Linux/Linux.sh norrun
  . $OPERATINGSYSTEMDIR/MS-DOS/MS-DOS.sh norrun
  . $OPERATINGSYSTEMDIR/Mac_OS_X/Mac_OS_X.sh norrun
  . $OPERATINGSYSTEMDIR/OpenBSD/OpenBSD.sh norrun
  . $OPERATINGSYSTEMDIR/Unix/Unix.sh norrun
  . $OPERATINGSYSTEMDIR/Windows/Windows.sh norrun

  KEYWORDS_OPERATINGSYSTEMS="operating(| )system|(^| )OS\b"
  KEYWORDS_OPERATINGSYSTEMS_OTHER="Net(| )BSD"
  KEYWORDS_OPERATINGSYSTEMS_EXCLUDE="$KEYWORDS_WINDOWS_ALL|$KEYWORDS_UNIX|$KEYWORDS_UNIX_SPECIAL|$KEYWORDS_LINUX_ALL|$KEYWORDS_MACOS|$KEYWORDS_OPENBSD|$KEYWORDS_FREEBSD|$KEYWORDS_MSDOS"
  KEYWORDS_OPERATINGSYSTEMS_ALL="$KEYWORDS_OPERATINGSYSTEMS|$KEYWORDS_OPERATINGSYSTEMS_OTHER|$KEYWORDS_OPERATINGSYSTEMS_EXCLUDE"

fi