#!/bin/bash

. ./catscripts/Lifestyle/Sports/Olympics/Olympics.sh norun

KEYWORDS_GREECE="Greece"
KEYWORDS_ANCIENTGREECE="Ancient(| )Gree(k|ce)"
KEYWORDS_ATHENS="Athens|Athenian"
KEYWORDS_ATHENS_EXCLUDE="Georgia|Texas|Ohio"
KEYWORDS_SPARTA="Sparta(|s|n)\b"
KEYWORDS_SPARTA_EXCLUDE="Halo"
KEYWORDS_SPARTA_EXCLUDE_CASESENSITVE="SPARTAN"
KEYWORDS_ANCIENTGREECE_EXCLUDE="$KEYWORDS_SPARTA|$KEYWORDS_ATHENS|$KEYWORDS_ANCIENTGREEKOLYMPICS"
KEYWORDS_GREECE_EXCLUDE="$KEYWORDS_ANCIENTGREECE|$KEYWORDS_ATHENS|$KEYWORDS_SPARTA"

if [ "$1" == "" ];
then
  
  debug_start "Greece"

  GREECE=$(egrep -i "$KEYWORDS_GREECE" "$NEWPAGES" | egrep -iv "$KEYWORDS_GREECE_EXCLUDE")
  ANCIENT=$(egrep -i "$KEYWORDS_ANCIENTGREECE" "$NEWPAGES" | egrep -iv "$KEYWORDS_ANCIENTGREECE_EXCLUDE")
  ATHENS=$(egrep -i "$KEYWORDS_ATHENS" "$NEWPAGES" | egrep -iv "$KEYWORDS_ATHENS_EXCLUDE")
  SPARTA=$(egrep -i "$KEYWORDS_SPARTA" "$NEWPAGES" | egrep -iv "$KEYWORDS_SPARTA_EXCLUDE" | egrep -v "$KEYWORDS_SPARTA_EXCLUDE_CASESENSITVE")

  categorize "GREECE" "Greece"
  categorize "ANCIENT" "Ancient Greece"
  categorize "ATHENS" "Athens"
  categorize "SPARTA" "Sparta"

  debug_end "Greece"

fi
