#!/bin/bash

POKEMONSPECIESDIR="./catscripts/Entertainment/Franchises/Pokémon/Pokémon_species"

if [ "$1" == "" ];
then

  debug_start "Pokémon species"

  . $POKEMONSPECIESDIR/A/A.sh  #KEYWORDS_POKEMONSPECIES_A
  . $POKEMONSPECIESDIR/B/B.sh  #KEYWORDS_POKEMONSPECIES_B
  . $POKEMONSPECIESDIR/C/C.sh  #KEYWORDS_POKEMONSPECIES_C
  . $POKEMONSPECIESDIR/D/D.sh  #KEYWORDS_POKEMONSPECIES_D
  . $POKEMONSPECIESDIR/E/E.sh  #KEYWORDS_POKEMONSPECIES_E
  . $POKEMONSPECIESDIR/F/F.sh  #KEYWORDS_POKEMONSPECIES_F
  . $POKEMONSPECIESDIR/G/G.sh  #KEYWORDS_POKEMONSPECIES_G
  . $POKEMONSPECIESDIR/H/H.sh  #KEYWORDS_POKEMONSPECIES_H
  . $POKEMONSPECIESDIR/I/I.sh  #KEYWORDS_POKEMONSPECIES_I
  . $POKEMONSPECIESDIR/J/J.sh  #KEYWORDS_POKEMONSPECIES_J
  . $POKEMONSPECIESDIR/K/K.sh  #KEYWORDS_POKEMONSPECIES_K
  . $POKEMONSPECIESDIR/L/L.sh  #KEYWORDS_POKEMONSPECIES_L
  . $POKEMONSPECIESDIR/M/M.sh  #KEYWORDS_POKEMONSPECIES_M
  . $POKEMONSPECIESDIR/N/N.sh  #KEYWORDS_POKEMONSPECIES_N
  . $POKEMONSPECIESDIR/O/O.sh  #KEYWORDS_POKEMONSPECIES_O
  . $POKEMONSPECIESDIR/P/P.sh  #KEYWORDS_POKEMONSPECIES_P
  . $POKEMONSPECIESDIR/Q/Q.sh  #KEYWORDS_POKEMONSPECIES_Q
  . $POKEMONSPECIESDIR/R/R.sh  #KEYWORDS_POKEMONSPECIES_R
  . $POKEMONSPECIESDIR/S/S.sh  #KEYWORDS_POKEMONSPECIES_S
  . $POKEMONSPECIESDIR/T/T.sh  #KEYWORDS_POKEMONSPECIES_T
  . $POKEMONSPECIESDIR/U/U.sh  #KEYWORDS_POKEMONSPECIES_U
  . $POKEMONSPECIESDIR/V/V.sh  #KEYWORDS_POKEMONSPECIES_V
  . $POKEMONSPECIESDIR/W/W.sh  #KEYWORDS_POKEMONSPECIES_W
  . $POKEMONSPECIESDIR/X/X.sh  #KEYWORDS_POKEMONSPECIES_X
  . $POKEMONSPECIESDIR/Y/Y.sh  #KEYWORDS_POKEMONSPECIES_Y
  . $POKEMONSPECIESDIR/Z/Z.sh  #KEYWORDS_POKEMONSPECIES_Z

  KEYWORDS_POKEMONSPECIES_ALL="$KEYWORDS_POKEMONSPECIES_A|$KEYWORDS_POKEMONSPECIES_B|$KEYWORDS_POKEMONSPECIES_C|$KEYWORDS_POKEMONSPECIES_D|$KEYWORDS_POKEMONSPECIES_E|$KEYWORDS_POKEMONSPECIES_F|$KEYWORDS_POKEMONSPECIES_G|$KEYWORDS_POKEMONSPECIES_H|$KEYWORDS_POKEMONSPECIES_I|$KEYWORDS_POKEMONSPECIES_J|$KEYWORDS_POKEMONSPECIES_K|$KEYWORDS_POKEMONSPECIES_L|$KEYWORDS_POKEMONSPECIES_M|$KEYWORDS_POKEMONSPECIES_N|$KEYWORDS_POKEMONSPECIES_O|$KEYWORDS_POKEMONSPECIES_P|$KEYWORDS_POKEMONSPECIES_Q|$KEYWORDS_POKEMONSPECIES_R|$KEYWORDS_POKEMONSPECIES_S|$KEYWORDS_POKEMONSPECIES_T|$KEYWORDS_POKEMONSPECIES_U|$KEYWORDS_POKEMONSPECIES_V|$KEYWORDS_POKEMONSPECIES_W|$KEYWORDS_POKEMONSPECIES_X|$KEYWORDS_POKEMONSPECIES_Y|$KEYWORDS_POKEMONSPECIES_Z"

  debug_end "Pokémon species"

else

  . $POKEMONSPECIESDIR/A/A.sh norun #KEYWORDS_POKEMONSPECIES_A
  . $POKEMONSPECIESDIR/B/B.sh norun #KEYWORDS_POKEMONSPECIES_B
  . $POKEMONSPECIESDIR/C/C.sh norun #KEYWORDS_POKEMONSPECIES_C
  . $POKEMONSPECIESDIR/D/D.sh norun #KEYWORDS_POKEMONSPECIES_D
  . $POKEMONSPECIESDIR/E/E.sh norun #KEYWORDS_POKEMONSPECIES_E
  . $POKEMONSPECIESDIR/F/F.sh norun #KEYWORDS_POKEMONSPECIES_F
  . $POKEMONSPECIESDIR/G/G.sh norun #KEYWORDS_POKEMONSPECIES_G
  . $POKEMONSPECIESDIR/H/H.sh norun #KEYWORDS_POKEMONSPECIES_H
  . $POKEMONSPECIESDIR/I/I.sh norun #KEYWORDS_POKEMONSPECIES_I
  . $POKEMONSPECIESDIR/J/J.sh norun #KEYWORDS_POKEMONSPECIES_J
  . $POKEMONSPECIESDIR/K/K.sh norun #KEYWORDS_POKEMONSPECIES_K
  . $POKEMONSPECIESDIR/L/L.sh norun #KEYWORDS_POKEMONSPECIES_L
  . $POKEMONSPECIESDIR/M/M.sh norun #KEYWORDS_POKEMONSPECIES_M
  . $POKEMONSPECIESDIR/N/N.sh norun #KEYWORDS_POKEMONSPECIES_N
  . $POKEMONSPECIESDIR/O/O.sh norun #KEYWORDS_POKEMONSPECIES_O
  . $POKEMONSPECIESDIR/P/P.sh norun #KEYWORDS_POKEMONSPECIES_P
  . $POKEMONSPECIESDIR/Q/Q.sh norun #KEYWORDS_POKEMONSPECIES_Q
  . $POKEMONSPECIESDIR/R/R.sh norun #KEYWORDS_POKEMONSPECIES_R
  . $POKEMONSPECIESDIR/S/S.sh norun #KEYWORDS_POKEMONSPECIES_S
  . $POKEMONSPECIESDIR/T/T.sh norun #KEYWORDS_POKEMONSPECIES_T
  . $POKEMONSPECIESDIR/U/U.sh norun #KEYWORDS_POKEMONSPECIES_U
  . $POKEMONSPECIESDIR/V/V.sh norun #KEYWORDS_POKEMONSPECIES_V
  . $POKEMONSPECIESDIR/W/W.sh norun #KEYWORDS_POKEMONSPECIES_W
  . $POKEMONSPECIESDIR/X/X.sh norun #KEYWORDS_POKEMONSPECIES_X
  . $POKEMONSPECIESDIR/Y/Y.sh norun #KEYWORDS_POKEMONSPECIES_Y
  . $POKEMONSPECIESDIR/Z/Z.sh norun #KEYWORDS_POKEMONSPECIES_Z

  KEYWORDS_POKEMONSPECIES_ALL="$KEYWORDS_POKEMONSPECIES_A|$KEYWORDS_POKEMONSPECIES_B|$KEYWORDS_POKEMONSPECIES_C|$KEYWORDS_POKEMONSPECIES_D|$KEYWORDS_POKEMONSPECIES_E|$KEYWORDS_POKEMONSPECIES_F|$KEYWORDS_POKEMONSPECIES_G|$KEYWORDS_POKEMONSPECIES_H|$KEYWORDS_POKEMONSPECIES_I|$KEYWORDS_POKEMONSPECIES_J|$KEYWORDS_POKEMONSPECIES_K|$KEYWORDS_POKEMONSPECIES_L|$KEYWORDS_POKEMONSPECIES_M|$KEYWORDS_POKEMONSPECIES_N|$KEYWORDS_POKEMONSPECIES_O|$KEYWORDS_POKEMONSPECIES_P|$KEYWORDS_POKEMONSPECIES_Q|$KEYWORDS_POKEMONSPECIES_R|$KEYWORDS_POKEMONSPECIES_S|$KEYWORDS_POKEMONSPECIES_T|$KEYWORDS_POKEMONSPECIES_U|$KEYWORDS_POKEMONSPECIES_V|$KEYWORDS_POKEMONSPECIES_W|$KEYWORDS_POKEMONSPECIES_X|$KEYWORDS_POKEMONSPECIES_Y|$KEYWORDS_POKEMONSPECIES_Z"

fi