#!/bin/bash

KEYWORDS_APOLLO11="Apollo(| )(11|XI)"
APOLLOELEVENDIR="$APOLLODIR/Apollo_11"

if [ "$1" == "" ];
then
  
  debug_start "Apollo 11"

  . "$APOLLOELEVENDIR/Neil_Armstrong/NeilArmstrong.sh" #KEYWORDS_NEILARMSTRONG_ALL
  . "$APOLLOELEVENDIR/Buzz_Aldrin/BuzzAldrin.sh" #KEYWORDS_BUZZALDRIN_ALL

  KEYWORDS_APOLLO11_EXCLUDE="$KEYWORDS_NEILARMSTRONG_ALL|$KEYWORDS_BUZZALDRIN_ALL"

  KEYWORDS_APOLLO11_ALL="$KEYWORDS_APOLLO11|$KEYWORDS_BUZZALDRIN_ALL|$KEYWORDS_NEILARMSTRONG_ALL"

  APOLLO11=$(egrep -i "$KEYWORDS_APOLLO11" "$NEWPAGES" | egrep -iv "$KEYWORDS_APOLLO11_EXCLUDE")

  categorize "APOLLO11" "Apollo 11"

  debug_end "Apollo 11"

else

  . "$APOLLOELEVENDIR/Neil_Armstrong/NeilArmstrong.sh" norun #KEYWORDS_NEILARMSTRONG_ALL
  . "$APOLLOELEVENDIR/Buzz_Aldrin/BuzzAldrin.sh" norun #KEYWORDS_BUZZALDRIN_ALL

  KEYWORDS_APOLLO11_EXCLUDE="$KEYWORDS_NEILARMSTRONG_ALL|$KEYWORDS_BUZZALDRIN_ALL"

  KEYWORDS_APOLLO11_ALL="$KEYWORDS_APOLLO11|$KEYWORDS_BUZZALDRIN_ALL|$KEYWORDS_NEILARMSTRONG_ALL"

fi