#!/bin/bash 
#Pokemon species by name, starting with the letter B

KEYWORDS_BAGON="Bagon"
KEYWORDS_BALTOY="Baltoy"
KEYWORDS_BANETTE="Banette"
KEYWORDS_BARBARACLE="Barbaracle"
KEYWORDS_BARBOACH="Barboach"
KEYWORDS_BASCULIN="Basculin"
KEYWORDS_BASTIODON="Bastiodon"
KEYWORDS_BAYLEEF="Bayleef"
KEYWORDS_BEARTIC="Beartic"
KEYWORDS_BEAUTIFLY="Beautifly"
KEYWORDS_BEEDRILL="Beedrill"
KEYWORDS_BEHEEYEM="Beheyeem"
KEYWORDS_BELDUM="Beldum"
KEYWORDS_BELLOSSOM="Bellossom"
KEYWORDS_BELLSPROUT="Bellsprout"
KEYWORDS_BERGMITE="Bergmite"
KEYWORDS_BIBAREL="Bibarel"
KEYWORDS_BIDOOF="Bidoof"
KEYWORDS_BINACLE="Binacle"
KEYWORDS_BISHARP="Bisharp"
KEYWORDS_BLASTOISE="Blastoise"
KEYWORDS_BLAZIKEN="Blaziken"
KEYWORDS_BLISSEY="Blissey"
KEYWORDS_BLITZLE="Blitzle"
KEYWORDS_BOLDORE="Boldore"
KEYWORDS_BONSLY="Bonsly"
KEYWORDS_BOUFFALANT="Bouf(|f)alant"
KEYWORDS_BRAIXEN="Braixen"
KEYWORDS_BRAVIARY="Braviary"
KEYWORDS_BRELOOM="Breloom"
KEYWORDS_BRONZONG="Bronzong"
KEYWORDS_BRONZOR="Bronzor"
KEYWORDS_BUDEW="Budew"
KEYWORDS_BUIZEL="Buizel"
KEYWORDS_BULBASAUR="Bulbasaur"
KEYWORDS_BUNEARY="Buneary"
KEYWORDS_BUNNELBY="Bunnelby"
KEYWORDS_BURMY="Burmy"
KEYWORDS_BUTTERFREE="Butterfree"
KEYWORDS_POKEMONSPECIES_B="$KEYWORDS_BAGON|$KEYWORDS_BALTOY|$KEYWORDS_BANETTE|$KEYWORDS_BARBARACLE|$KEYWORDS_BARBOACH|$KEYWORDS_BASCULIN|$KEYWORDS_BASTIODON|$KEYWORDS_BAYLEEF|$KEYWORDS_BEARTIC|$KEYWORDS_BEAUTIFLY|$KEYWORDS_BEEDRILL|$KEYWORDS_BEHEEYEM|$KEYWORDS_BELDUM|$KEYWORDS_BELLOSSOM|$KEYWORDS_BELLSPROUT|$KEYWORDS_BERGMITE|$KEYWORDS_BIBAREL|$KEYWORDS_BIDOOF|$KEYWORDS_BINACLE|$KEYWORDS_BISHARP|$KEYWORDS_BLASTOISE|$KEYWORDS_BLAZIKEN|$KEYWORDS_BLISSEY|$KEYWORDS_BLITZLE|$KEYWORDS_BOLDORE|$KEYWORDS_BOLDORE|$KEYWORDS_BONSLY|$KEYWORDS_BOUFFALANT|$KEYWORDS_BRAIXEN|$KEYWORDS_BRAVIARY|$KEYWORDS_BRELOOM|$KEYWORDS_BRONZONG|$KEYWORDS_BRONZOR|$KEYWORDS_BUDEW|$KEYWORDS_BUIZEL|$KEYWORDS_BULBASAUR|$KEYWORDS_BUNEARY|$KEYWORDS_BUNNELBY|$KEYWORDS_BURMY|$KEYWORDS_BUTTERFREE"

if [ "$1" == "" ]; #Normal operation
then

  debug_start "Pokemon B script"

  BAGON=$(egrep -i "$KEYWORDS_BAGON" "$NEWPAGES")
  BALTOY=$(egrep -i "$KEYWORDS_BALTOY" "$NEWPAGES")
  BANETTE=$(egrep -i "$KEYWORDS_BANETTE" "$NEWPAGES")
  BARBARACLE=$(egrep -i "$KEYWORDS_BARBARACLE" "$NEWPAGES")
  BARBOACH=$(egrep -i "$KEYWORDS_BARBOACH" "$NEWPAGES")
  BASCULIN=$(egrep -i "$KEYWORDS_BASCULIN" "$NEWPAGES")
  BASTIODON=$(egrep -i "$KEYWORDS_BASTIODON" "$NEWPAGES")
  BAYLEEF=$(egrep -i "$KEYWORDS_BAYLEEF" "$NEWPAGES")
  BEARTIC=$(egrep -i "$KEYWORDS_BEARTIC" "$NEWPAGES")
  BEAUTIFLY=$(egrep -i "$KEYWORDS_BEAUTIFLY" "$NEWPAGES")
  BEEDRILL=$(egrep -i "$KEYWORDS_BEEDRILL" "$NEWPAGES")
  BEHEEYEM=$(egrep -i "$KEYWORDS_BEHEEYEM" "$NEWPAGES")
  BELDUM=$(egrep -i "$KEYWORDS_BELDUM" "$NEWPAGES")
  BELLOSSOM=$(egrep -i "$KEYWORDS_BELLOSSOM" "$NEWPAGES")
  BELLSPROUT=$(egrep -i "$KEYWORDS_BELLSPROUT" "$NEWPAGES")
  BERGMITE=$(egrep -i "$KEYWORDS_BERGMITE" "$NEWPAGES")
  BIBAREL=$(egrep -i "$KEYWORDS_BIBAREL" "$NEWPAGES")
  BIDOOF=$(egrep -i "$KEYWORDS_BIDOOF" "$NEWPAGES")
  BINACLE=$(egrep -i "$KEYWORDS_BINACLE" "$NEWPAGES")
  BISHARP=$(egrep -i "$KEYWORDS_BISHARP" "$NEWPAGES")
  BLASTOISE=$(egrep -i "$KEYWORDS_BLASTOISE" "$NEWPAGES")
  BLAZIKEN=$(egrep -i "$KEYWORDS_BLAZIKEN" "$NEWPAGES")
  BLISSEY=$(egrep -i "$KEYWORDS_BLISSEY" "$NEWPAGES")
  BLITZLE=$(egrep -i "$KEYWORDS_BLITZLE" "$NEWPAGES")
  BOLDORE=$(egrep -i "$KEYWORDS_BOLDORE" "$NEWPAGES")
  BONSLY=$(egrep -i "$KEYWORDS_BONSLY" "$NEWPAGES")
  BOUFFALANT=$(egrep -i "$KEYWORDS_BOUFFALANT" "$NEWPAGES")
  BRAIXEN=$(egrep -i "$KEYWORDS_BRAIXEN" "$NEWPAGES")
  BRAVIARY=$(egrep -i "$KEYWORDS_BRAVIARY" "$NEWPAGES")
  BRELOOM=$(egrep -i "$KEYWORDS_BRELOOM" "$NEWPAGES")
  BRONZONG=$(egrep -i "$KEYWORDS_BRONZONG" "$NEWPAGES")
  BRONZOR=$(egrep -i "$KEYWORDS_BRONZOR" "$NEWPAGES")
  BUDEW=$(egrep -i "$KEYWORDS_BUDEW" "$NEWPAGES")
  BUIZEL=$(egrep -i "$KEYWORDS_BUIZEL" "$NEWPAGES")
  BULBASAUR=$(egrep -i "$KEYWORDS_BULBASAUR" "$NEWPAGES")
  BUNEARY=$(egrep -i "$KEYWORDS_BUNEARY" "$NEWPAGES")
  BUNNELBY=$(egrep -i "$KEYWORDS_BUNNELBY" "$NEWPAGES")
  BURMY=$(egrep -i "$KEYWORDS_BURMY" "$NEWPAGES")
  BUTTERFREE=$(egrep -i "$KEYWORDS_BUTTERFREE" "$NEWPAGES")


  categorize "BAGON" "Bagon"
  categorize "BALTOY" "Baltoy"
  categorize "BANETTE" "Banette"
  categorize "BARBARACLE" "Barbaracle"
  categorize "BARBOACH" "Barboach"
  categorize "BASCULIN" "Basculin"
  categorize "BASTIODON" "Bastiodon"
  categorize "BAYLEEF" "Bayleef"
  categorize "BEARTIC" "Beartic"
  categorize "BEAUTIFLY" "Beautifly"
  categorize "BEEDRILL" "Beedrill"
  categorize "BEHEEYEM" "Beheeyem"
  categorize "BELDUM" "Beldum"
  categorize "BELLOSSOM" "Bellossom"
  categorize "BELLSPROUT" "Bellsprout"
  categorize "BERGMITE" "Bergmite"
  categorize "BIBAREL" "Bibarel"
  categorize "BIDOOF" "Bidoof"
  categorize "BINACLE" "Binacle"
  categorize "BISHARP" "Bisharp"
  categorize "BLASTOISE" "Blastoise"
  categorize "BLAZIKEN" "Blaziken"
  categorize "BLISSEY" "Blissey"
  categorize "BLITZLE" "Blitzle"
  categorize "BOLDORE" "Boldore"
  categorize "BONSLY" "Bonsly"
  categorize "BOUFFALANT" "Bouffalant"
  categorize "BRAIXEN" "Braixen"
  categorize "BRAVIARY" "Braviary"
  categorize "BRELOOM" "Breloom"
  categorize "BRONZONG" "Bronzong"
  categorize "BRONZOR" "Bronzor"
  categorize "BUDEW" "Budew"
  categorize "BUIZEL" "Buizel"
  categorize "BULBASAUR" "Bulbasaur"
  categorize "BUNEARY" "Buneary"
  categorize "BUNNELBY" "Bunnelby"
  categorize "BURMY" "Burmy"
  categorize "BUTTERFREE" "Butterfree"

  debug_end "Pokemon B script"

fi