#!/bin/bash

KEYWORDS_ACTIVEDIRECTORY="Active(| )Directory|domain(| )controller|Windows(| )domain"
KEYWORDS_WINDOWS98="Windows(| )98|Win98"
KEYWORDS_WINDOWSNT="Windows(| )NT"
KEYWORDS_WINDOWS2000="Windows(| )2000|Win2000|W2k\b"
KEYWORDS_WINDOWSXP="Windows(| )XP|2000XP|WinXP"
KEYWORDS_WINDOWSSERVER2003="Windows(| )Server(| )2003|Windows(| )2003|Win(| )2003|Win(| )2k3|W2k3"
KEYWORDS_WINDOWSVISTA="Windows(| )Vista|Win(| )Vista"
KEYWORDS_WINDOWS7="Windows(| )7|Win7"
KEYWORDS_WINDOWSSERVER2008="Windows(| )Server(| )2008|Windows(| )2008|Win(| )2k8|W2k8"
KEYWORDS_WINDOWS8="Windows(| )8|Win8"
KEYWORDS_WINDOWS="Microsoft(| )Windows"
KEYWORDS_WINDOWSMEDIAPLAYER="Windows(| )Media(| )Player"
KEYWORDS_WINDOWSMOVIEMAKER="Windows(| )(DVD|Movie)(| )Maker|Windows(| )Live(| )(DVD|Movie)(| )Maker"
KEYWORDS_WINDOWSCASESENSITIVE="Windows"
KEYWORDS_WINDOWS_EXCLUDE="$KEYWORDS_ACTIVEDIRECTORY|$KEYWORDS_WINDOWSNT|$KEYWORDS_WINDOWS98|$KEYWORDS_WINDOWS2000|$KEYWORDS_WINDOWSXP|$KEYWORDS_WINDOWSVISTA|$KEYWORDS_WINDOWS7|$KEYWORDS_WINDOWS8|$KEYWORDS_WINDOWSSERVER2003|$KEYWORDS_WINDOWSSERVER2008|$KEYWORDS_WINDOWSMOVIEMAKER|\bX(-| )Windows|$KEYWORDS_WINDOWSMEDIAPLAYER"
KEYWORDS_WINDOWS_ALL="$KEYWORDS_WINDOWSCASESENSITIVE|$KEYWORDS_WINDOWS|$KEYWORDS_WINDOWS_EXCLUDE"

if [ "$1" == "" ];
then
  
  debug_start "Windows"

  ACTIVEDIRECTORY=$(egrep -i "$KEYWORDS_ACTIVEDIRECTORY" "$NEWPAGES")
  WINDOWS98=$(egrep -i "$KEYWORDS_WINDOWS98" "$NEWPAGES")
  WINDOWS2000=$(egrep -i "$KEYWORDS_WINDOWS2000" "$NEWPAGES")
  WINDOWSXP=$(egrep -i "$KEYWORDS_WINDOWSXP" "$NEWPAGES")
  WINDOWS2003=$(egrep -i "$KEYWORDS_WINDOWSSERVER2003" "$NEWPAGES")
  WINDOWSVISTA=$(egrep -i "$KEYWORDS_WINDOWSVISTA" "$NEWPAGES")
  WINDOWS7=$(egrep -i "$KEYWORDS_WINDOWS7" "$NEWPAGES")
  WINDOWS2008=$(egrep -i "$KEYWORDS_WINDOWSSERVER2008" "$NEWPAGES")
  WINDOWS8=$(egrep -i "$KEYWORDS_WINDOWS8" "$NEWPAGES")
  WINDOWSNT=$(egrep -i "$KEYWORDS_WINDOWSNT" "$NEWPAGES")
  WINDOWS=$(egrep -i "$KEYWORDS_WINDOWS" "$NEWPAGES" | egrep -iv "$KEYWORDS_WINDOWS_EXCLUDE" && egrep "$KEYWORDS_WINDOWSCASESENSITIVE" "$NEWPAGES" | egrep -iv "$KEYWORDS_WINDOWS_EXCLUDE")

  categorize "ACTIVEDIRECTORY" "Active Directory"
  categorize "WINDOWSNT" "Windows NT"
  categorize "WINDOWS98" "Windows 98"
  categorize "WINDOWS2000" "Windows 2000"
  categorize "WINDOWSXP" "Windows XP"
  categorize "WINDOWS2003" "Windows Server 2003"
  categorize "WINDOWSVISTA" "Windows Vista"
  categorize "WINDOWS7" "Windows 7"
  categorize "WINDOWS2008" "Windows Server 2008"
  categorize "WINDOWS8" "Windows 8"
  categorize "WINDOWS" "Windows"

  debug_end "Windows"

fi