#!/bin/bash

if [ "$DEBUG" == "yes" ];
then
  printf "Starting Countries\n" 
fi

CURRENTDIR="./catscripts/Government/Countries"

$CURRENTDIR/Afghanistan/Afghanistan.sh
$CURRENTDIR/Albania/Albania.sh
$CURRENTDIR/Algeria/Algeria.sh
$CURRENTDIR/Angola/Angola.sh
$CURRENTDIR/Argentina/Argentina.sh
$CURRENTDIR/Armenia/Armenia.sh
$CURRENTDIR/Australia/Australia.sh
$CURRENTDIR/Austria/Austria.sh
$CURRENTDIR/Azerbaijan/Azerbaijan.sh
$CURRENTDIR/Bahamas/Bahamas.sh
$CURRENTDIR/Bahrain/Bahrain.sh
$CURRENTDIR/Bangladesh/Bangladesh.sh
$CURRENTDIR/Barbados/Barbados.sh
$CURRENTDIR/Belgium/Belgium.sh
$CURRENTDIR/Belize/Belize.sh
$CURRENTDIR/Benin/Benin.sh
$CURRENTDIR/Bolivia/Bolivia.sh
$CURRENTDIR/Brazil/Brazil.sh
$CURRENTDIR/Brunei/Brunei.sh
$CURRENTDIR/Cambodia/Cambodia.sh
$CURRENTDIR/Cameroon/Cameroon.sh
$CURRENTDIR/Canada/Canada.sh
$CURRENTDIR/Chile/Chile.sh
$CURRENTDIR/China/China.sh
$CURRENTDIR/Costa_Rica/CostaRica.sh
$CURRENTDIR/Cuba/Cuba.sh
$CURRENTDIR/Cyprus/Cyprus.sh
$CURRENTDIR/Denmark/Denmark.sh
$CURRENTDIR/Dominican_Republic/DominicanRepublic.sh
$CURRENTDIR/Ecuador/Ecuador.sh
$CURRENTDIR/Egypt/Egypt.sh
$CURRENTDIR/El_Salvador/ElSalvador.sh
$CURRENTDIR/England/England.sh
$CURRENTDIR/Ethiopia/Ethiopia.sh
$CURRENTDIR/Fiji/Fiji.sh
$CURRENTDIR/Finland/Finland.sh
$CURRENTDIR/France/France.sh
$CURRENTDIR/Germany/Germany.sh
$CURRENTDIR/Ghana/Ghana.sh
$CURRENTDIR/Greece/Greece.sh
$CURRENTDIR/Guatemala/Guatemala.sh
$CURRENTDIR/Haiti/Haiti.sh
$CURRENTDIR/Honduras/Honduras.sh
$CURRENTDIR/Hungary/Hungary.sh
$CURRENTDIR/Iceland/Iceland.sh
$CURRENTDIR/India/India.sh
$CURRENTDIR/Indonesia/Indonesia.sh
$CURRENTDIR/Iran/Iran.sh
$CURRENTDIR/Iraq/Iraq.sh
$CURRENTDIR/Ireland/Ireland.sh
$CURRENTDIR/Israel/Israel.sh
$CURRENTDIR/Italy/Italy.sh
$CURRENTDIR/Ivory_Coast/IvoryCoast.sh
$CURRENTDIR/Jamaica/Jamaica.sh
$CURRENTDIR/Japan/Japan.sh
$CURRENTDIR/Jordan/Jordan.sh
$CURRENTDIR/Kenya/Kenya.sh
$CURRENTDIR/Laos/Laos.sh
$CURRENTDIR/Latvia/Latvia.sh
$CURRENTDIR/Lebanon/Lebanon.sh
$CURRENTDIR/Lesotho/Lesotho.sh
$CURRENTDIR/Libya/Libya.sh
$CURRENTDIR/Lithuania/Lithuania.sh
$CURRENTDIR/Luxembourg/Luxembourg.sh
$CURRENTDIR/Macedonia/Macedonia.sh
$CURRENTDIR/Madagascar/Madagascar.sh
$CURRENTDIR/Malaysia/Malaysia.sh
$CURRENTDIR/Mali/Mali.sh
$CURRENTDIR/Mexico/Mexico.sh
$CURRENTDIR/Morocco/Morocco.sh
$CURRENTDIR/Namibia/Namibia.sh
$CURRENTDIR/Nepal/Nepal.sh
$CURRENTDIR/New_Zealand/NewZealand.sh
$CURRENTDIR/Nicaragua/Nicaragua.sh
$CURRENTDIR/Nigeria/Nigeria.sh
$CURRENTDIR/Northern_Ireland/NorthernIreland.sh
$CURRENTDIR/North_Korea/NorthKorea.sh
$CURRENTDIR/Norway/Norway.sh
$CURRENTDIR/Paraguay/Paraguay.sh
$CURRENTDIR/Philippines/Philippines.sh
$CURRENTDIR/Poland/Poland.sh
$CURRENTDIR/Portugal/Portugal.sh
$CURRENTDIR/Singapore/Singapore.sh
$CURRENTDIR/South_Africa/SouthAfrica.sh
$CURRENTDIR/Spain/Spain.sh
$CURRENTDIR/Saudi_Arabia/SaudiArabia.sh
$CURRENTDIR/Scotland/Scotland.sh
$CURRENTDIR/South_Korea/SouthKorea.sh
$CURRENTDIR/Sri_Lanka/SriLanka.sh
$CURRENTDIR/Sweden/Sweden.sh
$CURRENTDIR/Switzerland/Switzerland.sh
$CURRENTDIR/Tanzia/Tanzia.sh
$CURRENTDIR/Tunisia/Tunisia.sh
$CURRENTDIR/Wales/Wales.sh
$CURRENTDIR/United_Arab_Emirates/UAE.sh
$CURRENTDIR/United_States/UnitedStates.sh
$CURRENTDIR/Unrecognized_countries/Unrecognized.sh
$CURRENTDIR/Venezuela/Venezuela.sh

if [ "$DEBUG" == "yes" ];
then
  printf "Finishing countries\n" 
fi