#!/bin/bash

CURRENTDIR="./catscripts/Government/Countries/"

$CURRENTDIR/Afghanistan/Afghanistan.sh
$CURRENTDIR/Albania/Albania.sh
$CURRENTDIR/Algeria/Algeria.sh
$CURRENTDIR/Argentina/Argentina.sh
$CURRENTDIR/Australia/Australia.sh
$CURRENTDIR/Bangladesh/Bangladesh.sh
$CURRENTDIR/Barbados/Barbados.sh
$CURRENTDIR/Belgium/Belgium.sh
$CURRENTDIR/Belize/Belize.sh
$CURRENTDIR/Brazil/Brazil.sh
$CURRENTDIR/Chile/Chile.sh
$CURRENTDIR/Cyprus/Cyprus.sh
$CURRENTDIR/Egypt/Egypt.sh
$CURRENTDIR/Ghana/Ghana.sh
$CURRENTDIR/Greece/Greece.sh
$CURRENTDIR/Haiti/Haiti.sh
$CURRENTDIR/Hungary/Hungary.sh
$CURRENTDIR/Iceland/Iceland.sh
$CURRENTDIR/Indonesia/Indonesia.sh
$CURRENTDIR/Iran/Iran.sh
$CURRENTDIR/Iraq/Iraq.sh
$CURRENTDIR/Jamaica/Jamaica.sh
$CURRENTDIR/Kenya/Kenya.sh
$CURRENTDIR/Latvia/Latvia.sh
$CURRENTDIR/Libya/Libya.sh
$CURRENTDIR/Lithuania/Lithuania.sh
$CURRENTDIR/Nepal/Nepal.sh
$CURRENTDIR/Nigeria/Nigeria.sh
$CURRENTDIR/Norway/Norway.sh
$CURRENTDIR/Philippines/Philippines.sh
$CURRENTDIR/Singapore/Singapore.sh 
$CURRENTDIR/Sweden/Sweden.sh
$CURRENTDIR/Tanzia/Tanzia.sh
$CURRENTDIR/Wales/Wales.sh
$CURRENTDIR/United_Arab_Emirates/UAE.sh
$CURRENTDIR/United_States/UnitedStates.sh
$CURRENTDIR/Unrecognized_countries/Unrecognized.sh