#!/bin/bash

./catscripts/Government/Countries/Afghanistan/Afghanistan.sh
./catscripts/Government/Countries/Albania/Albania.sh
./catscripts/Government/Countries/Algeria/Algeria.sh
./catscripts/Government/Countries/Argentina/Argentina.sh
./catscripts/Government/Countries/Australia/Australia.sh
./catscripts/Government/Countries/Bangladesh/Bangladesh.sh
./catscripts/Government/Countries/Barbados/Barbados.sh
./catscripts/Government/Countries/Belgium/Belgium.sh
./catscripts/Government/Countries/Belize/Belize.sh
./catscripts/Government/Countries/Brazil/Brazil.sh
./catscripts/Government/Countries/Chile/Chile.sh
./catscripts/Government/Countries/Cyprus/Cyprus.sh
./catscripts/Government/Countries/Egypt/Egypt.sh
./catscripts/Government/Countries/Ghana/Ghana.sh
./catscripts/Government/Countries/Greece/Greece.sh
./catscripts/Government/Countries/Haiti/Haiti.sh
./catscripts/Government/Countries/Hungary/Hungary.sh
./catscripts/Government/Countries/Iceland/Iceland.sh
./catscripts/Government/Countries/Indonesia/Indonesia.sh
./catscripts/Government/Countries/Iran/Iran.sh
./catscripts/Government/Countries/Iraq/Iraq.sh
./catscripts/Government/Countries/Jamaica/Jamaica.sh
./catscripts/Government/Countries/Kenya/Kenya.sh
./catscripts/Government/Countries/Libya/Libya.sh
./catscripts/Government/Countries/Nepal/Nepal.sh
./catscripts/Government/Countries/Nigeria/Nigeria.sh
./catscripts/Government/Countries/Norway/Norway.sh
./catscripts/Government/Countries/Philippines/Philippines.sh
./catscripts/Government/Countries/Singapore/Singapore.sh 
./catscripts/Government/Countries/Sweden/Sweden.sh
./catscripts/Government/Countries/Tanzia/Tanzia.sh
./catscripts/Government/Countries/Wales/Wales.sh
./catscripts/Government/Countries/United\ States/UnitedStates.sh
./catscripts/Government/Countries/Unrecognized_countries/Unrecognized.sh