#!/bin/bash
#Pokemon species by name, starting with the letter C

KEYWORDS_CACNEA="Cacnea"
KEYWORDS_CACTURNE="Cacturne"
KEYWORDS_CAMERUPT="Camerupt"
KEYWORDS_CARBINK="Carbink"
KEYWORDS_CARNIVINE="Carnivine"
KEYWORDS_CARRACOSTA="Car(|r)acosta"
KEYWORDS_CARVANHA="Car(c|v|b)anha"
KEYWORDS_CASCOON="Cascoon"
KEYWORDS_CASTFORM="Castform"
KEYWORDS_CATERPIE="Caterpie"
KEYWORDS_CELEBI="Celebi"
KEYWORDS_CHANDELURE="Chandelure"
KEYWORDS_CHANSEY="Chansey"
KEYWORDS_CHARIZARD="Charizard"
KEYWORDS_CHARMANDER="Charmander"
KEYWORDS_CHARMELEON="Charmeleon"
KEYWORDS_CHATOT="Chatot"
KEYWORDS_CHERRIM="Cherrim"
KEYWORDS_CHERUBI="Cherubi\b|Cherubi's|Cherubis\b"
KEYWORDS_CHESNAUGHT="Chesnaught"
KEYWORDS_CHESPIN="Chespin"
KEYWORDS_CHIKORITA="Chikorita"
KEYWORDS_CHIMCHAR="Chimchar"
KEYWORDS_CHIMECHO="Chimecho"
KEYWORDS_CHINCHOU="Chinchou"
KEYWORDS_CHINGLING="Chingling"
KEYWORDS_CINCCINO="Cinccino"
KEYWORDS_CLAMPERL="Clamperl"
KEYWORDS_CLAUNCHER="Clauncher"
KEYWORDS_CLAUNCHER_CASESENSITIVE_EXCLUDE="CLauncher"
KEYWORDS_CLAYDOL="Claydol"
KEYWORDS_CLEFABLE="Clefable"
KEYWORDS_CLEFAIRY="Clefairy"
KEYWORDS_CLEFFA="Cleffa"
KEYWORDS_CLOYSTER="Cloyster"
KEYWORDS_COBALION="Cobalion"
KEYWORDS_COFAGRIGUS="Cofagrigus|Confagrigus"
KEYWORDS_COMBEE="Combee"
KEYWORDS_COMBUSKEN="Combusken"
KEYWORDS_CONKELDURR="Conkeldurr"
KEYWORDS_CORPHISH="Corphish"
KEYWORDS_CORSOLA="Corsola"
KEYWORDS_COTTONEE="Cottonee"
KEYWORDS_CRADILY="Cradily"
KEYWORDS_CRANIDOS="Cranidos"
KEYWORDS_CRAWDAUNT="Crawdaunt"
KEYWORDS_CRESSELIA="Cresselia"
KEYWORDS_CROAGUNK="Croagunk"
KEYWORDS_CROBAT="\bCrobat"
KEYWORDS_CROCONAW="Croconaw"
KEYWORDS_CRUSTLE="Crustle"
KEYWORDS_CRYOGONAL="Cryogonal"
KEYWORDS_CUBCHOO="Cubchoo"
KEYWORDS_CUBONE="Cubone"
KEYWORDS_CYNDAQUIL="Cyndaquil"
KEYWORDS_POKEMONSPECIES_C="$KEYWORDS_CACNEA|$KEYWORDS_CACTURNE|$KEYWORDS_CAMERUPT|$KEYWORDS_CARBINK|$KEYWORDS_CARNIVINE|$KEYWORDS_CARRACOSTA|$KEYWORDS_CARVANHA|$KEYWORDS_CASCOON|$KEYWORDS_CASTFORM|$KEYWORDS_CATERPIE|$KEYWORDS_CELEBI|$KEYWORDS_CHANDELURE|$KEYWORDS_CHANSEY|$KEYWORDS_CHARIZARD|$KEYWORDS_CHARMANDER|$KEYWORDS_CHARMELEON|$KEYWORDS_CHATOT|$KEYWORDS_CHERRIM|$KEYWORDS_CHERUBI||$KEYWORDS_CHESNAUGHT|$KEYWORDS_CHESPIN|$KEYWORDS_CHIKORITA|$KEYWORDS_CHIMCHAR|$KEYWORDS_CHIMECHO|$KEYWORDS_CHINCHOU|$KEYWORDS_CHINGLING|$KEYWORDS_CINCCINO|$KEYWORDS_CLAMPERL|$KEYWORDS_CLAUNCHER|$KEYWORDS_CLAYDOL|$KEYWORDS_CLEFABLE|$KEYWORDS_CLEFAIRY|$KEYWORDS_CLEFFA|$KEYWORDS_CLOYSTER|$KEYWORDS_COBALION|$KEYWORDS_COFAGRIGUS|$KEYWORDS_COMBEE|$KEYWORDS_COMBUSKEN|$KEYWORDS_CONKELDURR|$KEYWORDS_CORPHISH|$KEYWORDS_CORSOLA|$KEYWORDS_COTTONEE|$KEYWORDS_CRADILY|$KEYWORDS_CRANIDOS|$KEYWORDS_CRAWDAUNT|$KEYWORDS_CRESSELIA|$KEYWORDS_CROAGUNK|$KEYWORDS_CROBAT|$KEYWORDS_CROCONAW|$KEYWORDS_CRUSTLE|$KEYWORDS_CRYOGONAL|$KEYWORDS_CUBCHOO|$KEYWORDS_CUBONE|$KEYWORDS_CYNDAQUIL"

if [ "$1" == "" ]; #Normal run
then

  debug_start "Pokemon C script"

  CACNEA=$(egrep -i "$KEYWORDS_CACNEA" "$NEWPAGES")
  CACTURNE=$(egrep -i "$KEYWORDS_CACTURNE" "$NEWPAGES")
  CAMERUPT=$(egrep -i "$KEYWORDS_CAMERUPT" "$NEWPAGES")
  CARBINK=$(egrep -i "$KEYWORDS_CARBINK" "$NEWPAGES")
  CARNIVINE=$(egrep -i "$KEYWORDS_CARNIVINE" "$NEWPAGES")
  CARRACOSTA=$(egrep -i "$KEYWORDS_CARRACOSTA" "$NEWPAGES")
  CARVANHA=$(egrep -i "$KEYWORDS_CARVANHA" "$NEWPAGES")
  CASCOON=$(egrep -i "$KEYWORDS_CASCOON" "$NEWPAGES")
  CASTFORM=$(egrep -i "$KEYWORDS_CASTFORM" "$NEWPAGES")
  CATERPIE=$(egrep -i "$KEYWORDS_CATERPIE" "$NEWPAGES")
  CELEBI=$(egrep -i "$KEYWORDS_CELEBI" "$NEWPAGES")
  CHANDELURE=$(egrep -i "$KEYWORDS_CHANDELURE" "$NEWPAGES")
  CHANSEY=$(egrep -i "$KEYWORDS_CHANSEY" "$NEWPAGES")
  CHARIZARD=$(egrep -i "$KEYWORDS_CHARIZARD" "$NEWPAGES")
  CHARMANDER=$(egrep -i "$KEYWORDS_CHARMANDER" "$NEWPAGES")
  CHARMELEON=$(egrep -i "$KEYWORDS_CHARMELEON" "$NEWPAGES")
  CHATOT=$(egrep -i "$KEYWORDS_CHATOT" "$NEWPAGES")
  CHERRIM=$(egrep -i "$KEYWORDS_CHERRIM" "$NEWPAGES")
  CHERUBI=$(egrep -i "$KEYWORDS_CHERUBI" "$NEWPAGES")
  CHESNAUGHT=$(egrep -i "$KEYWORDS_CHESNAUGHT" "$NEWPAGES")
  CHESPIN=$(egrep -i "$KEYWORDS_CHESPIN" "$NEWPAGES")
  CHIKORITA=$(egrep -i "$KEYWORDS_CHIKORITA" "$NEWPAGES")
  CHIMCHAR=$(egrep -i "$KEYWORDS_CHIMCHAR" "$NEWPAGES")
  CHIMECHO=$(egrep -i "$KEYWORDS_CHIMECHO" "$NEWPAGES")
  CHINCHOU=$(egrep -i "$KEYWORDS_CHINCHOU" "$NEWPAGES")
  CHINGLING=$(egrep -i "$KEYWORDS_CHINGLING" "$NEWPAGES")
  CINCCINO=$(egrep -i "$KEYWORDS_CINCCINO" "$NEWPAGES")
  CLAMPERL=$(egrep -i "$KEYWORDS_CLAMPERL" "$NEWPAGES")
  CLAUNCHER=$(egrep -i "$KEYWORDS_CLAUNCHER" "$NEWPAGES"| egrep -v "$KEYWORDS_CLAUNCHER_CASESENSITIVE_EXCLUDE") 
  CLAYDOL=$(egrep -i "$KEYWORDS_CLAYDOL" "$NEWPAGES")
  CLEFABLE=$(egrep -i "$KEYWORDS_CLEFABLE" "$NEWPAGES")
  CLEFAIRY=$(egrep -i "$KEYWORDS_CLEFAIRY" "$NEWPAGES")
  CLEFFA=$(egrep -i "$KEYWORDS_CLEFFA" "$NEWPAGES")
  CLOYSTER=$(egrep -i "$KEYWORDS_CLOYSTER" "$NEWPAGES")
  COBALION=$(egrep -i "$KEYWORDS_COBALION" "$NEWPAGES")
  COFAGRIGUS=$(egrep -i "$KEYWORDS_COFAGRIGUS" "$NEWPAGES")
  COMBEE=$(egrep -i "$KEYWORDS_COMBEE" "$NEWPAGES")
  COMBUSKEN=$(egrep -i "$KEYWORDS_COMBUSKEN" "$NEWPAGES")
  CONKELDURR=$(egrep -i "$KEYWORDS_CONKELDURR" "$NEWPAGES")
  CORPHISH=$(egrep -i "$KEYWORDS_CORPHISH" "$NEWPAGES")
  CORSOLA=$(egrep -i "$KEYWORDS_CORSOLA" "$NEWPAGES")
  COTTONEE=$(egrep -i "$KEYWORDS_COTTONEE" "$NEWPAGES")
  CRADILY=$(egrep -i "$KEYWORDS_CRADILY" "$NEWPAGES")
  CRANIDOS=$(egrep -i "$KEYWORDS_CRANIDOS" "$NEWPAGES")
  CRAWDAUNT=$(egrep -i "$KEYWORDS_CRAWDAUNT" "$NEWPAGES")
  CRESSELIA=$(egrep -i "$KEYWORDS_CRESSELIA" "$NEWPAGES")
  CROAGUNK=$(egrep -i "$KEYWORDS_CROAGUNK" "$NEWPAGES")
  CROBAT=$(egrep -i "$KEYWORDS_CROBAT" "$NEWPAGES")
  CROCONAW=$(egrep -i "$KEYWORDS_CROCONAW" "$NEWPAGES")
  CRUSTLE=$(egrep -i "$KEYWORDS_CRUSTLE" "$NEWPAGES")
  CRYOGONAL=$(egrep -i "$KEYWORDS_CRYOGONAL" "$NEWPAGES")
  CUBCHOO=$(egrep -i "$KEYWORDS_CUBCHOO" "$NEWPAGES")
  CUBONE=$(egrep -i "$KEYWORDS_CUBONE" "$NEWPAGES")
  CYNDAQUIL=$(egrep -i "$KEYWORDS_CYNDAQUIL" "$NEWPAGES")

  categorize "CACNEA" "Cacnea"
  categorize "CACTURNE" "Cacturne"
  categorize "CAMERUPT" "Camerupt"
  categorize "CARBINK" "Carbink"
  categorize "CARNIVINE" "Carnivine"
  categorize "CARRACOSTA" "Carracosta"
  categorize "CARVANHA" "Carvanha"
  categorize "CASCOON" "Cascoon"
  categorize "CASTFORM" "Castform"
  categorize "CATERPIE" "Caterpie"
  categorize "CELEBI" "Celebi"
  categorize "CHANDELURE" "Chandelure"
  categorize "CHANSEY" "Chansey"
  categorize "CHARIZARD" "Charizard"
  categorize "CHARMANDER" "Charmander"
  categorize "CHARMELEON" "Charmeleon"
  categorize "CHATOT" "Chatot"
  categorize "CHERRIM" "Cherrim"
  categorize "CHERUBI" "Cherubi"
  categorize "CHESNAUGHT" "Chesnaught"
  categorize "CHESPIN" "Chespin"
  categorize "CHIKORITA" "Chikorita"
  categorize "CHIMCHAR" "Chimchar"
  categorize "CHIMECHO" "Chimecho"
  categorize "CHINCHOU" "Chinchou"
  categorize "CHINGLING" "Chingling"
  categorize "CINCCINO" "Cinccino"
  categorize "CLAMPERL" "Clamperl"
  categorize "CLAUNCHER" "Clauncher"
  categorize "CLAYDOL" "Claydol"
  categorize "CLEFABLE" "Clefable"
  categorize "CLEFAIRY" "Clefairy"
  categorize "CLEFFA" "Cleffa"
  categorize "CLOYSTER" "Cloyster"
  categorize "COBALION" "Cobalion"
  categorize "COFAGRIGUS" "Cofagrigus"
  categorize "COMBEE" "Combee"
  categorize "COMBUSKEN" "Combusken"
  categorize "CONKELDURR" "Conkeldurr"
  categorize "CORPHISH" "Corphish"
  categorize "CORSOLA" "Corsola"
  categorize "COTTONEE" "Cottonee"
  categorize "CRADILY" "Cradily"
  categorize "CRANIDOS" "Cranidos"
  categorize "CRAWDAUNT" "Crawdaunt"
  categorize "CRESSELIA" "Cresselia"
  categorize "CROAGUNK" "Croagunk"
  categorize "CROBAT" "Crobat"
  categorize "CROCONAW" "Croconaw"
  categorize "CRUSTLE" "Crustle"
  categorize "CRYOGONAL" "Cryogonal"
  categorize "CUBCHOO" "Cubchoo"
  categorize "CUBONE" "Cubone"
  categorize "CYNDAQUIL" "Cyndaquil"

  debug_end "Pokemon C script"

fi