#!/bin/bash

KEYWORDS_GERMANY="Germany"
KEYWORDS_NAZIGERMANY="Nazi"
KEYWORDS_HITLER="Hitler"
KEYWORDS_NAZIGERMANY_SECONDARY="Hitler(| )youth"
KEYWORDS_HITLER_EXCLUDE="$KEYWORDS_NAZIGERMANY_SECONDARY"
KEYWORDS_BERLIN="Berlin"
KEYWORDS_AUSCHWITZ="Auschwitz|Oświęcim"
KEYWORDS_ANNEFRANK="(Anne|Otto)(| )Frank"
KEYWORDS_NAZIGERMANY_EXCLUDE="$KEYWORDS_HITLER|$KEYWORDS_AUSCHWITZ|$KEYWORDS_ANNEFRANK"
KEYWORDS_GERMANY_EXCLUDE="$KEYWORDS_NAZIGERMANY|$KEYWORDS_HITLER|$KEYWORDS_NAZIGERMANY_SECONDARY|$KEYWORDS_AUSCHWITZ|$KEYWORDS_BERLIN"

KEYWORDS_GERMANY_ALL="$KEYWORDS_GERMANY|$KEYWORDS_NAZIGERMANY|$KEYWORDS_HITLER|$KEYWORDS_NAZIGERMANY_SECONDARY|$KEYWORDS_BERLIN|$KEYWORDS_AUSCHWITZ"

if [ "$1" == "" ]; #Normal operation
then
  
  debug_start "Germany"

  GERMANY=$(egrep -i "$KEYWORDS_GERMANY" "$NEWPAGES" | egrep -iv "$KEYWORDS_GERMANY_EXCLUDE")
  NAZI=$(egrep -i "$KEYWORDS_NAZIGERMANY" "$NEWPAGES" | egrep -iv "$KEYWORDS_NAZIGERMANY_EXCLUDE" && egrep -i "$KEYWORDS_NAZIGERMANY_SECONDARY" "$NEWPAGES")
  HITLER=$(egrep -i "$KEYWORDS_HITLER" "$NEWPAGES" | egrep -iv "$KEYWORDS_HITLER_EXCLUDE")
  ANNEFRANK=$(egrep -i "$KEYWORDS_ANNEFRANK" "$NEWPAGES")
  BERLIN=$(egrep -i "$KEYWORDS_BERLIN" "$NEWPAGES")

  categorize "GERMANY" "Germany"
  categorize "NAZI" "Nazi Germany"
  categorize "HITLER" "Adolf Hitler"
  categorize "ANNEFRANK" "Anne Frank"
  categorize "BERLIN" "Berlin"

  debug_end "Germany"

fi
