#!/bin/bash

KEYWORDS_SAUDIARABIA="Saudi(| )Arabia"
KEYWORDS_MECCA="Mecca"
KEYWORDS_MEDINA="Medina"
KEYWORDS_RIYADH="Riyadh"
KEYWORDS_SAUDIARABIA_EXCLUDE="$KEYWORDS_MECCA|$KEYWORDS_MEDINA|$KEYWORDS_RIYADH"
KEYWORDS_SAUDIARABIA_ALL="$KEYWORDS_SAUDIARABIA|$KEYWORDS_MECCA|$KEYWORDS_MEDINA|$KEYWORDS_RIYADH"

if [ "$1" == "" ];
then
  
  debug_start "Saudi Arabia"

  SAUDIARABIA=$(egrep -i "$KEYWORDS_SAUDIARABIA" "$NEWPAGES" | egrep -iv "$KEYWORDS_SAUDIARABIA_EXCLUDE")
  MECCA=$(egrep -i "$KEYWORDS_MECCA" "$NEWPAGES")
  MEDINA=$(egrep -i "$KEYWORDS_MEDINA" "$NEWPAGES")
  RIYADH=$(egrep -i "$KEYWORDS_RIYADH" "$NEWPAGES")

  categorize "SAUDIARABIA" "Saudi Arabia"
  categorize "MECCA" "Mecca"
  categorize "MEDINA" "Medina"
  categorize "RIYADH" "Riyadh"

  debug_end "Saudi Arabia"

fi