#!/bin/bash

KEYWORDS_PACHIRISU="Pachirisu"
KEYWORDS_PALKIA="Palkia"
KEYWORDS_PALPITOAD="Palpitoad"
KEYWORDS_PANCHAM="Pancham"
KEYWORDS_PANGORO="Pangoro"
KEYWORDS_PANPOUR="Panpour"
KEYWORDS_PANSAGE="Pansage"
KEYWORDS_PANSEAR="Pansear"
KEYWORDS_PARAS="Paras\b"
KEYWORDS_PARASECT="Parasect"
KEYWORDS_PATRAT="Patrat"
KEYWORDS_PAWNIARD="Pawniard"
KEYWORDS_PELIPPER="Pelipper"
KEYWORDS_PERSIAN="Persian\b"
KEYWORDS_PERSIAN_EXCLUDE="empire|language|speak|cat|kitten|gulf|language|religion|in(| )Persian$|capital|leader|war|Persian(| )ruler"
KEYWORDS_PETILIL="Petilil"
KEYWORDS_PHANPY="Phanpy"
KEYWORDS_PHANTUMP="Phantump"
KEYWORDS_PHIONE="Phione"
KEYWORDS_PICHU="Pichu"
KEYWORDS_PIDOVE="P(e|i)dove"
KEYWORDS_PIDGEOT="Pidgeot\b"
KEYWORDS_PIDGEOTTO="Pidgeot(|t)o"
KEYWORDS_PIDGEY="Pidgey"
KEYWORDS_PIGNITE="Pignite"
KEYWORDS_PIKACHU="Pikachu"
KEYWORDS_PILOSWINE="Piloswine"
KEYWORDS_PINECO="Pineco\b"
KEYWORDS_PINSIR="Pinsir"
KEYWORDS_PIPLUP="Piplup"
KEYWORDS_PLUSLE="Plusle"
KEYWORDS_POLITOED="Politoed"
KEYWORDS_POLIWAG="Poliwag"
KEYWORDS_POLIWHIRL="Poliwhirl"
KEYWORDS_POLIWRATH="Poliwrath"
KEYWORDS_PONYTA="Ponyta\b"
KEYWORDS_POOCHYENA="Poochyena"
KEYWORDS_PORYGON="Porygon"
KEYWORDS_PORYGONZ="Porygon-Z"
KEYWORDS_PORYGON2="Porygon2"
KEYWORDS_PRIMEAPE="Primeape"
KEYWORDS_PRINPLUP="Prinplup"
KEYWORDS_PROBOPASS="Probopass"
KEYWORDS_PSYDUCK="Psyduck"
KEYWORDS_PUMPKABOO="Pumpkaboo"
KEYWORDS_PUPITAR="Pupitar"
KEYWORDS_PURRLOIN="Purrloin"
KEYWORDS_PURUGLY="Purugly"
KEYWORDS_PYROAR="Pyroar"
KEYWORDS_POKEMONSPECIES_P="$KEYWORDS_PACHIRISU|$KEYWORDS_PALKIA|$KEYWORDS_PALPITOAD|$KEYWORDS_PANCHAM|$KEYWORDS_PANGORO|$KEYWORDS_PANPOUR|$KEYWORDS_PANSAGE|$KEYWORDS_PANSEAR|$KEYWORDS_PARAS|$KEYWORDS_PARASECT|$KEYWORDS_PATRAT|$KEYWORDS_PAWNIARD|$KEYWORDS_PELIPPER|$KEYWORDS_PERSIAN|$KEYWORDS_PETILIL|$KEYWORDS_PHANPY|$KEYWORDS_PHANTUMP|$KEYWORDS_PHIONE|$KEYWORDS_PICHU|$KEYWORDS_PIDGEOT|$KEYWORDS_PIDGEOTTO|$KEYWORDS_PIDGEY|$KEYWORDS_PIDOVE|$KEYWORDS_PIGNITE|$KEYWORDS_PIKACHU|$KEYWORDS_PILOSWINE|$KEYWORDS_PINECO|$KEYWORDS_PINSIR|$KEYWORDS_PIPLUP|$KEYWORDS_PLUSLE|$KEYWORDS_POLITOED|$KEYWORDS_POLIWAG|$KEYWORDS_POLIWHIRL|$KEYWORDS_POLIWRATH|$KEYWORDS_PONYTA|$KEYWORDS_POOCHYENA|$KEYWORDS_PORYGON|$KEYWORDS_PORYGON2|$KEYWORDS_PORYGONZ|$KEYWORDS_PRIMEAPE|$KEYWORDS_PRINPLUP|$KEYWORDS_PROBOPASS|$KEYWORDS_PSYDUCK|$KEYWORDS_PUMPKABOO|$KEYWORDS_PUPITAR|$KEYWORDS_PURRLOIN|$KEYWORDS_PURUGLY|$KEYWORDS_PYROAR"

if [ "$1" == "" ];
then

  debug_start "Pokemon 'P' scripts"

  PACHIRISU=$(egrep -i "$KEYWORDS_PACHIRISU" "$NEWPAGES")
  PALKIA=$(egrep -i "$KEYWORDS_PALKIA" "$NEWPAGES")
  PALPITOAD=$(egrep -i "$KEYWORDS_PALPITOAD" "$NEWPAGES")
  PANCHAM=$(egrep -i "$KEYWORDS_PANCHAM" "$NEWPAGES")
  PANGORO=$(egrep -i "$KEYWORDS_PANGORO" "$NEWPAGES")
  PANPOUR=$(egrep -i "$KEYWORDS_PANPOUR" "$NEWPAGES")
  PANSAGE=$(egrep -i "$KEYWORDS_PANSAGE" "$NEWPAGES")
  PANSEAR=$(egrep -i "$KEYWORDS_PANSEAR" "$NEWPAGES")
  PARAS=$(egrep -i "$KEYWORDS_PARAS" "$NEWPAGES")
  PARASECT=$(egrep -i "$KEYWORDS_PARASECT" "$NEWPAGES")
  PATRAT=$(egrep -i "$KEYWORDS_PATRAT" "$NEWPAGES")
  PAWNIARD=$(egrep -i "$KEYWORDS_PAWNIARD" "$NEWPAGES")
  PELIPPER=$(egrep -i "$KEYWORDS_PELIPPER" "$NEWPAGES")
  PERSIAN=$(egrep -i "$KEYWORDS_PERSIAN" "$NEWPAGES" | egrep -iv "$KEYWORDS_PERSIAN_EXCLUDE")
  PETILIL=$(egrep -i "$KEYWORDS_PETILIL" "$NEWPAGES")
  PHANPY=$(egrep -i "$KEYWORDS_PHANPY" "$NEWPAGES")
  PHANTUMP=$(egrep -i "$KEYWORDS_PHANTUMP" "$NEWPAGES")
  PHIONE=$(egrep -i "$KEYWORDS_PHIONE" "$NEWPAGES")
  PICHU=$(egrep -i "$KEYWORDS_PICHU" "$NEWPAGES")
  PIDGEOT=$(egrep -i "$KEYWORDS_PIDGEOT" "$NEWPAGES")
  PIDGEOTTO=$(egrep -i "$KEYWORDS_PIDGEOTTO" "$NEWPAGES")
  PIDGEY=$(egrep -i "$KEYWORDS_PIDGEY" "$NEWPAGES")
  PIDOVE=$(egrep -i "$KEYWORDS_PIDOVE" "$NEWPAGES")
  PIGNITE=$(egrep -i "$KEYWORDS_PIGNITE" "$NEWPAGES")
  PIKACHU=$(egrep -i "$KEYWORDS_PIKACHU" "$NEWPAGES")
  PILOSWINE=$(egrep -i "$KEYWORDS_PILOSWINE" "$NEWPAGES")
  PINECO=$(egrep -i "$KEYWORDS_PINECO" "$NEWPAGES")
  PINSIR=$(egrep -i "$KEYWORDS_PINSIR" "$NEWPAGES")
  PIPLUP=$(egrep -i "$KEYWORDS_PIPLUP" "$NEWPAGES")
  PLUSLE=$(egrep -i "$KEYWORDS_PLUSLE" "$NEWPAGES")
  POLITOED=$(egrep -i "$KEYWORDS_POLITOED" "$NEWPAGES")
  POLIWAG=$(egrep -i "$KEYWORDS_POLIWAG" "$NEWPAGES")
  POLIWHIRL=$(egrep -i "$KEYWORDS_POLIWHIRL" "$NEWPAGES")
  POLIWRATH=$(egrep -i "$KEYWORDS_POLIWRATH" "$NEWPAGES")
  PONYTA=$(egrep -i "$KEYWORDS_PONYTA" "$NEWPAGES")
  POOCHYENA=$(egrep -i "$KEYWORDS_POOCHYENA" "$NEWPAGES")
  PORYGON=$(egrep -i "$KEYWORDS_PORYGON" "$NEWPAGES")
  PORYGONZ=$(egrep -i "$KEYWORDS_PORYGONZ" "$NEWPAGES")
  PORYGON2=$(egrep -i "$KEYWORDS_PORYGON2" "$NEWPAGES")
  PRIMEAPE=$(egrep -i "$KEYWORDS_PRIMEAPE" "$NEWPAGES")
  PRINPLUP=$(egrep -i "$KEYWORDS_PRINPLUP" "$NEWPAGES")
  PROBOPASS=$(egrep -i "$KEYWORDS_PROBOPASS" "$NEWPAGES")
  PSYDUCK=$(egrep -i "$KEYWORDS_PSYDUCK" "$NEWPAGES")
  PUMPKABOO=$(egrep -i "$KEYWORDS_PUMPKABOO" "$NEWPAGES")
  PUPITAR=$(egrep -i "$KEYWORDS_PUPITAR" "$NEWPAGES")
  PURRLOIN=$(egrep -i "$KEYWORDS_PURRLOIN" "$NEWPAGES")
  PURUGLY=$(egrep -i "$KEYWORDS_PURUGLY" "$NEWPAGES")
  PYROAR=$(egrep -i "$KEYWORDS_PYROAR" "$NEWPAGES")

  categorize "PACHIRISU" "Pachirisu"
  categorize "PALKIA" "Palkia"
  categorize "PALPITOAD" "Palpitoad"
  categorize "PANCHAM" "Pancham"
  categorize "PANGORO" "Pangoro"
  categorize "PANPOUR" "Panpour"
  categorize "PANSAGE" "Pansage"
  categorize "PANSEAR" "Pansear"
  categorize "PARAS" "Paras"
  categorize "PARASECT" "Parasect"
  categorize "PATRAT" "Patrat"
  categorize "PAWNIARD" "Pawniard"
  categorize "PELIPPER" "Pelipper"
  categorize "PERSIAN" "Persian"
  categorize "PETILIL" "Petilil"
  categorize "PHANPY" "Phanpy"
  categorize "PHANTUMP" "Phantump"
  categorize "PHIONE" "Phione"
  categorize "PICHU" "Pichu"
  categorize "PIDGEOT" "Pidgeot"
  categorize "PIDGEOTTO" "Pidgeotto"
  categorize "PIDGEY" "Pidgey"
  categorize "PIDOVE" "Pidove"
  categorize "PIGNITE" "Pignite"
  categorize "PIKACHU" "Pikachu"
  categorize "PILOSWINE" "Piloswine"
  categorize "PINECO" "Pineco"
  categorize "PINSIR" "Pinsir"
  categorize "PIPLUP" "Piplup"
  categorize "PLUSLE" "Plusle"
  categorize "POLITOED" "Politoed"
  categorize "POLIWAG" "Poliwag"
  categorize "POLIWHIRL" "Poliwhirl"
  categorize "POLIWRATH" "Poliwrath"
  categorize "PONYTA" "Ponyta"
  categorize "POOCHYENA" "Poochyena"
  categorize "PORYGON" "Porygon"
  categorize "PORYGONZ" "Porygon-Z"
  categorize "PORYGON2" "Porygon2"
  categorize "PRIMEAPE" "Primeape"
  categorize "PRINPLUP" "Prinplup"
  categorize "PROBOPASS" "Probopass"
  categorize "PSYDUCK" "Psyduck"
  categorize "PUMPKABOO" "Pumpkaboo"
  categorize "PUPITAR" "Pupitar"
  categorize "PURRLOIN" "Purrloin"
  categorize "PURUGLY" "Purugly"
  categorize "PYROAR" "Pyroar"

  debug_end "Pokemon 'P' scripts"

fi