#!/bin/bash

KEYWORDS_PLACENTALMAMMALS="Placental(| )mammal"

if [ "$1" == "" ];
then
  
  debug_start "Placental mammals"

  PLACENTALDIR="$MAMMALDIR/Placental_mammals"

  . $PLACENTALDIR/Aardvarks/Aardvarks.sh #KEYWORDS_AARDVARKS_ALL
  . $PLACENTALDIR/Armadillos/Armadillos.sh #KEYWORDS_ARMADILLOS_ALL
  . $PLACENTALDIR/Bats/Bats.sh #KEYWORDS_BATS_ALL
  . $PLACENTALDIR/Dolphins/Dolphins.sh #KEYWORDS_DOLPHINS
  . $PLACENTALDIR/Hedgehogs/Hedgehogs.sh #KEYWORDS_HEDGEHOGS_ALL

  KEYWORDS_PLACENTALEXCLUDE="$KEYWORDS_AARDVARKS_ALL|$KEYWORDS_ARMADILLOS_ALL|$KEYWORDS_BATS_ALL|$KEYWORDS_DOLPHINS|$KEYWORDS_HEDGEHOGS_ALL"
  KEYWORDS_PLACENTALMAMMALS_ALL="$KEYWORDS_PLACENTALMAMMALS|$KEYWORDS_AARDVARKS_ALL|$KEYWORDS_ARMADILLOS_ALL|$KEYWORDS_BATS_ALL|$KEYWORDS_DOLPHINS|$KEYWORDS_HEDGEHOGS_ALL"

  debug_end "Placental mammals"

fi