#!/bin/bash

KEYWORDS_PLACENTALMAMMALS="Placental(| )mammal"

if [ "$1" == "" ];
then
  
  debug_start "Placental mammals"

  PLACENTALDIR="$MAMMALDIR/Placental_mammals"

  . $PLACENTALDIR/Aardvarks/Aardvarks.sh #KEYWORDS_AARDVARKS_ALL
  . $PLACENTALDIR/Anteaters/Anteaters.sh #KEYWORDS_ANTEATERS_ALL
  . $PLACENTALDIR/Armadillos/Armadillos.sh #KEYWORDS_ARMADILLOS_ALL
  . $PLACENTALDIR/Bats/Bats.sh #KEYWORDS_BATS_ALL
  . $PLACENTALDIR/Dolphins/Dolphins.sh #KEYWORDS_DOLPHINS
  . $PLACENTALDIR/Dugongs/Dugongs.sh #KEYWORDS_DUGONGS_ALL
  . $PLACENTALDIR/Elephants/Elephants.sh #KEYWORDS_ELEPHANTS_ALL
  . $PLACENTALDIR/Hedgehogs/Hedgehogs.sh #KEYWORDS_HEDGEHOGS_ALL
  . $PLACENTALDIR/Manatees/Manatees.sh #KEYWORDS_MANATEES_ALL
  . $PLACENTALDIR/Rabbits/Rabbits.sh #KEYWORDS_RABBITS_ALL
  . $PLACENTALDIR/Shrews/Shrews.sh #KEYWORDS_SHREWS_ALL
  . $PLACENTALDIR/Sloths/Sloths.sh #KEYWORDS_SLOTHS_ALL

  KEYWORDS_PLACENTALEXCLUDE="$KEYWORDS_AARDVARKS_ALL|$KEYWORDS_ANTEATERS_ALL|$KEYWORDS_ARMADILLOS_ALL|$KEYWORDS_BATS_ALL|$KEYWORDS_DOLPHINS|$KEYWORDS_DUGONGS_ALL|$KEYWORDS_ELEPHANTS_ALL|$KEYWORDS_HEDGEHOGS_ALL|$KEYWORDS_MANATEES_ALL|$KEYWORDS_RABBITS_ALL|$KEYWORDS_SHREWS_ALL|$KEYWORDS_SLOTHS_ALL"
  KEYWORDS_PLACENTALMAMMALS_ALL="$KEYWORDS_PLACENTALMAMMALS|$KEYWORDS_AARDVARKS_ALL|$KEYWORDS_ANTEATERS_ALL|$KEYWORDS_ARMADILLOS_ALL|$KEYWORDS_BATS_ALL|$KEYWORDS_DOLPHINS|$KEYWORDS_DUGONGS_ALL|$KEYWORDS_ELEPHANTS_ALL|$KEYWORDS_HEDGEHOGS_ALL|$KEYWORDS_MANATEES_ALL|$KEYWORDS_RABBITS_ALL|$KEYWORDS_SHREWS_ALL|$KEYWORDS_SLOTHS_ALL"

  debug_end "Placental mammals"

fi