#!/bin/bash

KEYWORDS_MONSTERHUNTERSERIES="Monster(| )Hunter"
KEYWORDS_MONSTERHUNTERTWO="Monster(| )Hunter(| )2\b|MH2\b"
KEYWORDS_MONSTERHUNTERFREEDOM="Monster(| )Hunter(| )Freedom"
KEYWORDS_MONSTERHUNTERFREEDOMTWO="Monster(| )Hunter(| )Freedom(| )2|\bMHF2\b"
KEYWORDS_MONSTERHUNTERFREEDOMUNITE="Monster(| )Hunter(| )Freedom(| )Unit.|\bMHFU\b" #The . instead of an 'e' is intentional
KEYWORDS_MONSTERHUNTERFREEDOM_EXCLUDE="$KEYWORDS_MONSTERHUNTERFREEDOMTWO|$KEYWORDS_MONSTERHUNTERFREEDOMUNITE"
KEYWORDS_MONSTERHUNTERFRONTIER="Monster(| )Hunter(| )Frontier"
KEYWORDS_MONSTERHUNTERTRI="Monster(| )Hunter(| )(Tri|3)|\bMH3"
KEYWORDS_MONSTERHUNTERSERIES_EXCLUDE="$KEYWORDS_MONSTERHUNTERTWO|$KEYWORDS_MONSTERHUNTERTRI|$KEYWORDS_MONSTERHUNTERFREEDOM|$KEYWORDS_MONSTERHUNTERFREEDOMUNITE|$KEYWORDS_MONSTERHUNTERFREEDOMTWO|$KEYWORDS_MONSTERHUNTERFRONTIER"

if [ "$1" == "" ];
then

  debug_start "Monster Hunter series"

  SERIES=$(egrep -i "$KEYWORDS_MONSTERHUNTERSERIES" "$NEWPAGES" | egrep -iv "$KEYWORDS_MONSTERHUNTERSERIES_EXCLUDE" )
  MH2=$(egrep -i "$KEYWORDS_MONSTERHUNTERTWO" "$NEWPAGES")
  FREEDOM=$(egrep -i "$KEYWORDS_MONSTERHUNTERFREEDOM" "$NEWPAGES" | egrep -iv "$KEYWORDS_MONSTERHUNTERFREEDOM_EXCLUDE")
  MHFU=$(egrep -i "$KEYWORDS_MONSTERHUNTERFREEDOMUNITE" "$NEWPAGES")
  MHF2=$(egrep -i "$KEYWORDS_MONSTERHUNTERFREEDOMTWO" "$NEWPAGES")
  FRONTIER=$(egrep -i "$KEYWORDS_MONSTERHUNTERFRONTIER" "$NEWPAGES")
  TRI=$(egrep -i "$KEYWORDS_MONSTERHUNTERTRI" "$NEWPAGES")

  categorize "SERIES" "Monster Hunter series"
  categorize "MH2" "Monster Hunter 2"
  categorize "FREEDOM" "Monster Hunter Freedom"
  categorize "MHFU" "Monster Hunter Freedom Unite"
  categorize "MHF2" "Monster Hunter Freedom 2"
  categorize "FRONTIER" "Monster Hunter Frontier"
  categorize "TRI" "Monster Hunter Tri"

  debug_end "Monster Hunter series"

fi