#!/bin/bash

GENERALMOTORSDIR="$MANUFACTURERDIR/General_Motors"

. $GENERALMOTORSDIR/Cadillac/Cadillac.sh #KEYWORDS_CADILLAC_ALL
. $GENERALMOTORSDIR/Chevrolet/Chevrolet.sh
. $GENERALMOTORSDIR/GMC/GMC.sh
