#!/bin/bash

USSTATESDIR="./catscripts/Government/Countries/United_States/US_states"

$USSTATESDIR/Alabama/Alabama.sh
$USSTATESDIR/Alaska/Alaska.sh
$USSTATESDIR/Arizona/Arizona.sh
$USSTATESDIR/Arkansas/Arkansas.sh
$USSTATESDIR/California/California.sh
$USSTATESDIR/Colorado/Colorado.sh
$USSTATESDIR/Connecticut/Connecticut.sh
$USSTATESDIR/Delaware/Delaware.sh
$USSTATESDIR/Florida/Florida.sh
$USSTATESDIR/Georgia/Georgia.sh
$USSTATESDIR/Hawaii/Hawaii.sh
$USSTATESDIR/Idaho/Idaho.sh
$USSTATESDIR/Illinois/Illinois.sh
$USSTATESDIR/Indiana/Indiana.sh
$USSTATESDIR/Iowa/Iowa.sh
$USSTATESDIR/Kansas/Kansas.sh
$USSTATESDIR/Kentucky/Kentucky.sh
$USSTATESDIR/Louisiana/Louisiana.sh
$USSTATESDIR/Michigan/Michigan.sh
$USSTATESDIR/Maine/Maine.sh
$USSTATESDIR/Maryland/Maryland.sh
$USSTATESDIR/Massachusetts/Massachusetts.sh
$USSTATESDIR/Minnesota/Minnesota.sh
$USSTATESDIR/Mississippi/Mississippi.sh
$USSTATESDIR/Missouri/Missouri.sh
$USSTATESDIR/Montana/Montana.sh
$USSTATESDIR/Nebraska/Nebraska.sh
$USSTATESDIR/Nevada/Nevada.sh
$USSTATESDIR/New_Jersey/NewJersey.sh
$USSTATESDIR/New_Mexico/NewMexico.sh
$USSTATESDIR/New_York/NewYork.sh
$USSTATESDIR/North_Carolina/NorthCarolina.sh
$USSTATESDIR/North_Dakota/NorthDakota.sh
$USSTATESDIR/Ohio/Ohio.sh
$USSTATESDIR/Oklahoma/Oklahoma.sh
$USSTATESDIR/Oregon/Oregon.sh
$USSTATESDIR/Pennsylvania/Pennsylvania.sh
$USSTATESDIR/Rhode_Island/RhodeIsland.sh
$USSTATESDIR/South_Carolina/SouthCarolina.sh
$USSTATESDIR/South_Dakota/SouthDakota.sh
$USSTATESDIR/Texas/Texas.sh
$USSTATESDIR/Utah/Utah.sh
$USSTATESDIR/Vermont/Vermont.sh
$USSTATESDIR/Virginia/Virginia.sh
$USSTATESDIR/Washington/Washington.sh
$USSTATESDIR/West_Virginia/WestVirginia.sh
$USSTATESDIR/Wisconsin/Wisconsin.sh
$USSTATESDIR/Wyoming/Wyoming.sh
