#!/bin/bash

USSTATESDIR="$UNITEDSTATESDIR/US_states"

KEYWORDS_USSTATES="(U(|\.)S(|\.)|United(| )States)(| )state(|s)"

if [ "$1" == "" ];
then

  debug_start "US states"

.  "$USSTATESDIR/Alabama/Alabama.sh" #KEYWORDS_ALABAMA_ALL
.  "$USSTATESDIR/Alaska/Alaska.sh" #KEYWORDS_ALASKA_ALL
.  "$USSTATESDIR/Arizona/Arizona.sh" #KEYWORDS_ARIZONA_ALL
.  "$USSTATESDIR/Arkansas/Arkansas.sh" #KEYWORDS_ARKANSAS_ALL
.  "$USSTATESDIR/California/California.sh" #KEYWORDS_CALIFORNIA_ALL
.  "$USSTATESDIR/Colorado/Colorado.sh" #KEYWORDS_COLORADO_ALL
.  "$USSTATESDIR/Connecticut/Connecticut.sh" #KEYWORDS_CONNECTICUT_ALL
.  "$USSTATESDIR/Delaware/Delaware.sh" #KEYWORDS_DELAWARE_ALL
.  "$USSTATESDIR/Florida/Florida.sh" #KEYWORDS_FLORIDA_ALL
.  "$USSTATESDIR/Georgia/Georgia.sh" #KEYWORDS_GEORGIA_ALL
.  "$USSTATESDIR/Hawaii/Hawaii.sh" #KEYWORDS_HAWAII_ALL
.  "$USSTATESDIR/Idaho/Idaho.sh" #KEYWORDS_IDAHO_ALL
.  "$USSTATESDIR/Illinois/Illinois.sh" #KEYWORDS_ILLINOIS_ALL
.  "$USSTATESDIR/Indiana/Indiana.sh" #KEYWORDS_INDIANA_ALL
.  "$USSTATESDIR/Iowa/Iowa.sh" #KEYWORDS_IOWA_ALL
.  "$USSTATESDIR/Kansas/Kansas.sh" #KEYWORDS_KANSAS_ALL
.  "$USSTATESDIR/Kentucky/Kentucky.sh" #KEYWORDS_KENTUCKY_ALL
.  "$USSTATESDIR/Louisiana/Louisiana.sh" #KEYWORDS_LOUISIANA_ALL
.  "$USSTATESDIR/Maine/Maine.sh" #KEYWORDS_MAINE_ALL
.  "$USSTATESDIR/Maryland/Maryland.sh" #KEYWORDS_MARYLAND_ALL
.  "$USSTATESDIR/Massachusetts/Massachusetts.sh" #KEYWORDS_MASSACHUSETTS_ALL
.  "$USSTATESDIR/Michigan/Michigan.sh" #KEYWORDS_MICHIGAN_ALL
.  "$USSTATESDIR/Minnesota/Minnesota.sh" #KEYWORDS_MINNESOTA_ALL
.  "$USSTATESDIR/Mississippi/Mississippi.sh" #KEYWORDS_MISSISSIPPI_ALL
.  "$USSTATESDIR/Missouri/Missouri.sh" #KEYWORDS_MISSOURI_ALL
.  "$USSTATESDIR/Montana/Montana.sh" #KEYWORDS_MONTANA_ALL
.  "$USSTATESDIR/Nebraska/Nebraska.sh" #KEYWORDS_NEBRASKA_ALL
.  "$USSTATESDIR/Nevada/Nevada.sh" #KEYWORDS_NEVADA_ALL
.  "$USSTATESDIR/New_Hampshire/NewHampshire.sh" #KEYWORDS_NEWHAMPSHIRE_ALL
.  "$USSTATESDIR/New_Jersey/NewJersey.sh" #KEYWORDS_NEWJERSEY_ALL
.  "$USSTATESDIR/New_Mexico/NewMexico.sh" #KEYWORDS_NEWMEXICO_ALL
.  "$USSTATESDIR/New_York/NewYork.sh" #KEYWORDS_NEWYORK_ALL
.  "$USSTATESDIR/North_Carolina/NorthCarolina.sh" #KEYWORDS_NORTHCAROLINA_ALL
.  "$USSTATESDIR/North_Dakota/NorthDakota.sh" #KEYWORDS_NORTHDAKOTA_ALL
.  "$USSTATESDIR/Ohio/Ohio.sh" #KEYWORDS_OHIO_ALL
.  "$USSTATESDIR/Oklahoma/Oklahoma.sh" #KEYWORDS_OKLAHOMA_ALL
.  "$USSTATESDIR/Oregon/Oregon.sh" #KEYWORDS_OREGON_ALL
.  "$USSTATESDIR/Pennsylvania/Pennsylvania.sh" #KEYWORDS_PENNSYLVANIA_ALL
.  "$USSTATESDIR/Rhode_Island/RhodeIsland.sh" #KEYWORDS_RHODEISLAND_ALL
.  "$USSTATESDIR/South_Carolina/SouthCarolina.sh" #KEYWORDS_SOUTHCAROLINA_ALL
.  "$USSTATESDIR/South_Dakota/SouthDakota.sh" #KEYWORDS_SOUTHDAKOTA_ALL
.  "$USSTATESDIR/Tennessee/Tennessee.sh" #KEYWORDS_TENNESSEE_ALL
.  "$USSTATESDIR/Texas/Texas.sh" #KEYWORDS_TEXAS_ALL
.  "$USSTATESDIR/Utah/Utah.sh" #KEYWORDS_UTAH_ALL
.  "$USSTATESDIR/Vermont/Vermont.sh" #KEYWORDS_VERMONT_ALL
.  "$USSTATESDIR/Virginia/Virginia.sh" #KEYWORDS_VIRGINIA_ALL
.  "$USSTATESDIR/Washington/Washington.sh" #KEYWORDS_WASHINGTON_ALL
.  "$USSTATESDIR/West_Virginia/WestVirginia.sh" #KEYWORDS_WESTVIRGINIA_ALL
.  "$USSTATESDIR/Wisconsin/Wisconsin.sh" #KEYWORDS_WISCONSIN_ALL
.  "$USSTATESDIR/Wyoming/Wyoming.sh" #KEYWORDS_WYOMING_ALL

  KEYWORDS_USSTATES_EXCLUDE="$KEYWORDS_ALABAMA_ALL|$KEYWORDS_ALASKA_ALL|$KEYWORDS_ARIZONA_ALL|$KEYWORDS_ARKANSAS_ALL|$KEYWORDS_CALIFORNIA_ALL|$KEYWORDS_COLORADO_ALL|$KEYWORDS_CONNECTICUT_ALL|$KEYWORDS_DELAWARE_ALL|$KEYWORDS_FLORIDA_ALL|$KEYWORDS_GEORGIA_ALL|$KEYWORDS_HAWAII_ALL|$KEYWORDS_IDAHO_ALL|$KEYWORDS_ILLINOIS_ALL|$KEYWORDS_INDIANA_ALL|$KEYWORDS_IOWA_ALL|$KEYWORDS_KANSAS_ALL|$KEYWORDS_KENTUCKY_ALL|$KEYWORDS_LOUISIANA_ALL|$KEYWORDS_MAINE_ALL|$KEYWORDS_MARYLAND_ALL|$KEYWORDS_MASSACHUSETTS_ALL|$KEYWORDS_MICHIGAN_ALL|$KEYWORDS_MINNESOTA_ALL|$KEYWORDS_MISSISSIPPI_ALL|$KEYWORDS_MISSOURI_ALL|$KEYWORDS_MONTANA_ALL|$KEYWORDS_NEBRASKA_ALL|$KEYWORDS_NEVADA_ALL|$KEYWORDS_NEWHAMPSHIRE_ALL|$KEYWORDS_NEWJERSEY_ALL|$KEYWORDS_NEWMEXICO_ALL|$KEYWORDS_NEWYORK_ALL|$KEYWORDS_NORTHCAROLINA_ALL|$KEYWORDS_NORTHDAKOTA_ALL|$KEYWORDS_OHIO_ALL|$KEYWORDS_OKLAHOMA_ALL|$KEYWORDS_OREGON_ALL|$KEYWORDS_PENNSYLVANIA_ALL|$KEYWORDS_RHODEISLAND_ALL|$KEYWORDS_SOUTHCAROLINA_ALL|$KEYWORDS_SOUTHDAKOTA_ALL|$KEYWORDS_TENNESSEE_ALL|$KEYWORDS_TEXAS_ALL|$KEYWORDS_UTAH_ALL|$KEYWORDS_VERMONT_ALL|$KEYWORDS_VIRGINIA_ALL|$KEYWORDS_WASHINGTON_ALL|$KEYWORDS_WESTVIRGINIA_ALL|$KEYWORDS_WISCONSIN_ALL|$KEYWORDS_WYOMING_ALL"
  KEYWORDS_USSTATES_ALL="$KEYWORDS_USSTATES|$KEYWORDS_USSTATES_EXCLUDE"

  USSTATES=$(egrep -i "$KEYWORDS_USSTATES" "$NEWPAGES" | egrep -iv "$KEYWORDS_USSTATES_EXCLUDE")

  categorize "USSTATES" "US states"

  debug_end "US states"

else

.  "$USSTATESDIR/Alabama/Alabama.sh" norun #KEYWORDS_ALABAMA_ALL
.  "$USSTATESDIR/Alaska/Alaska.sh" norun #KEYWORDS_ALASKA_ALL
.  "$USSTATESDIR/Arizona/Arizona.sh" norun #KEYWORDS_ARIZONA_ALL
.  "$USSTATESDIR/Arkansas/Arkansas.sh" norun #KEYWORDS_ARKANSAS_ALL
.  "$USSTATESDIR/California/California.sh" norun #KEYWORDS_CALIFORNIA_ALL
.  "$USSTATESDIR/Colorado/Colorado.sh" norun #KEYWORDS_COLORADO_ALL
.  "$USSTATESDIR/Connecticut/Connecticut.sh" norun #KEYWORDS_CONNECTICUT_ALL
.  "$USSTATESDIR/Delaware/Delaware.sh" norun #KEYWORDS_DELAWARE_ALL
.  "$USSTATESDIR/Florida/Florida.sh" norun #KEYWORDS_FLORIDA_ALL
.  "$USSTATESDIR/Georgia/Georgia.sh" norun #KEYWORDS_GEORGIA_ALL
.  "$USSTATESDIR/Hawaii/Hawaii.sh" norun #KEYWORDS_HAWAII_ALL
.  "$USSTATESDIR/Idaho/Idaho.sh norun" #KEYWORDS_IDAHO_ALL
.  "$USSTATESDIR/Illinois/Illinois.sh" norun #KEYWORDS_ILLINOIS_ALL
.  "$USSTATESDIR/Indiana/Indiana.sh" norun #KEYWORDS_INDIANA_ALL
.  "$USSTATESDIR/Iowa/Iowa.sh" norun #KEYWORDS_IOWA_ALL
.  "$USSTATESDIR/Kansas/Kansas.sh" norun #KEYWORDS_KANSAS_ALL
.  "$USSTATESDIR/Kentucky/Kentucky.sh" norun #KEYWORDS_KENTUCKY_ALL
.  "$USSTATESDIR/Louisiana/Louisiana.sh" norun #KEYWORDS_LOUISIANA_ALL
.  "$USSTATESDIR/Maine/Maine.sh" norun #KEYWORDS_MAINE_ALL
.  "$USSTATESDIR/Maryland/Maryland.sh" norun #KEYWORDS_MARYLAND_ALL
.  "$USSTATESDIR/Massachusetts/Massachusetts.sh" norun #KEYWORDS_MASSACHUSETTS_ALL
.  "$USSTATESDIR/Michigan/Michigan.sh" norun #KEYWORDS_MICHIGAN_ALL
.  "$USSTATESDIR/Minnesota/Minnesota.sh" norun #KEYWORDS_MINNESOTA_ALL
.  "$USSTATESDIR/Mississippi/Mississippi.sh" norun #KEYWORDS_MISSISSIPPI_ALL
.  "$USSTATESDIR/Missouri/Missouri.sh" norun #KEYWORDS_MISSOURI_ALL
.  "$USSTATESDIR/Montana/Montana.sh" norun #KEYWORDS_MONTANA_ALL
.  "$USSTATESDIR/Nebraska/Nebraska.sh" norun #KEYWORDS_NEBRASKA_ALL
.  "$USSTATESDIR/Nevada/Nevada.sh" norun #KEYWORDS_NEVADA_ALL
.  "$USSTATESDIR/New_Hampshire/NewHampshire.sh" norun #KEYWORDS_NEWHAMPSHIRE_ALL
.  "$USSTATESDIR/New_Jersey/NewJersey.sh" norun #KEYWORDS_NEWJERSEY_ALL
.  "$USSTATESDIR/New_Mexico/NewMexico.sh" norun #KEYWORDS_NEWMEXICO_ALL
.  "$USSTATESDIR/New_York/NewYork.sh" norun #KEYWORDS_NEWYORK_ALL
.  "$USSTATESDIR/North_Carolina/NorthCarolina.sh" norun #KEYWORDS_NORTHCAROLINA_ALL
.  "$USSTATESDIR/North_Dakota/NorthDakota.sh" norun #KEYWORDS_NORTHDAKOTA_ALL
.  "$USSTATESDIR/Ohio/Ohio.sh" norun #KEYWORDS_OHIO_ALL
.  "$USSTATESDIR/Oklahoma/Oklahoma.sh" norun #KEYWORDS_OKLAHOMA_ALL
.  "$USSTATESDIR/Oregon/Oregon.sh" norun #KEYWORDS_OREGON_ALL
.  "$USSTATESDIR/Pennsylvania/Pennsylvania.sh" norun #KEYWORDS_PENNSYLVANIA_ALL
.  "$USSTATESDIR/Rhode_Island/RhodeIsland.sh" norun #KEYWORDS_RHODEISLAND_ALL
.  "$USSTATESDIR/South_Carolina/SouthCarolina.sh" norun #KEYWORDS_SOUTHCAROLINA_ALL
.  "$USSTATESDIR/South_Dakota/SouthDakota.sh" norun #KEYWORDS_SOUTHDAKOTA_ALL
.  "$USSTATESDIR/Tennessee/Tennessee.sh" norun #KEYWORDS_TENNESSEE_ALL
.  "$USSTATESDIR/Texas/Texas.sh" norun #KEYWORDS_TEXAS_ALL
.  "$USSTATESDIR/Utah/Utah.sh" norun #KEYWORDS_UTAH_ALL
.  "$USSTATESDIR/Vermont/Vermont.sh" norun #KEYWORDS_VERMONT_ALL
.  "$USSTATESDIR/Virginia/Virginia.sh" norun #KEYWORDS_VIRGINIA_ALL
.  "$USSTATESDIR/Washington/Washington.sh" norun #KEYWORDS_WASHINGTON_ALL
.  "$USSTATESDIR/West_Virginia/WestVirginia.sh" norun #KEYWORDS_WESTVIRGINIA_ALL
.  "$USSTATESDIR/Wisconsin/Wisconsin.sh" norun #KEYWORDS_WISCONSIN_ALL
.  "$USSTATESDIR/Wyoming/Wyoming.sh" norun #KEYWORDS_WYOMING_ALL

fi
