#!/bin/bash

CURRENTDIR="./catscripts/Government/Countries/United_States/US_states"

$CURRENTDIR/Alabama/Alabama.sh
$CURRENTDIR/Alaska/Alaska.sh
$CURRENTDIR/Arizona/Arizona.sh
$CURRENTDIR/Arkansas/Arkansas.sh
$CURRENTDIR/California/California.sh
$CURRENTDIR/Colorado/Colorado.sh
$CURRENTDIR/Connecticut/Connecticut.sh
$CURRENTDIR/Delaware/Delaware.sh
$CURRENTDIR/Florida/Florida.sh
$CURRENTDIR/Georgia/Georgia.sh
$CURRENTDIR/Hawaii/Hawaii.sh
$CURRENTDIR/Idaho/Idaho.sh
$CURRENTDIR/Illinois/Illinois.sh
$CURRENTDIR/Indiana/Indiana.sh
$CURRENTDIR/Iowa/Iowa.sh
$CURRENTDIR/Kansas/Kansas.sh
$CURRENTDIR/Kentucky/Kentucky.sh
$CURRENTDIR/Louisiana/Louisiana.sh
$CURRENTDIR/Michigan/Michigan.sh
$CURRENTDIR/Maine/Maine.sh
$CURRENTDIR/Maryland/Maryland.sh
$CURRENTDIR/Massachusetts/Massachusetts.sh
$CURRENTDIR/Minnesota/Minnesota.sh
$CURRENTDIR/Mississippi/Mississippi.sh
$CURRENTDIR/Missouri/Missouri.sh
$CURRENTDIR/Montana/Montana.sh
$CURRENTDIR/Nebraska/Nebraska.sh
$CURRENTDIR/Nevada/Nevada.sh
$CURRENTDIR/New_Jersey/NewJersey.sh
$CURRENTDIR/New_Mexico/NewMexico.sh
$CURRENTDIR/New_York/NewYork.sh
$CURRENTDIR/North_Carolina/NorthCarolina.sh
$CURRENTDIR/North_Dakota/NorthDakota.sh
$CURRENTDIR/Ohio/Ohio.sh
$CURRENTDIR/Oklahoma/Oklahoma.sh
$CURRENTDIR/Oregon/Oregon.sh
$CURRENTDIR/Pennsylvania/Pennsylvania.sh
$CURRENTDIR/Rhode_Island/RhodeIsland.sh
$CURRENTDIR/South_Carolina/SouthCarolina.sh
$CURRENTDIR/South_Dakota/SouthDakota.sh
$CURRENTDIR/Texas/Texas.sh
$CURRENTDIR/Utah/Utah.sh
$CURRENTDIR/Vermont/Vermont.sh
$CURRENTDIR/Wisconsin/Wisconsin.sh
$CURRENTDIR/Wyoming/Wyoming.sh
