#!/bin/bash

KEYWORDS_ACTINIUM="\bActinium"
KEYWORDS_THORIUM="Thorium"
KEYWORDS_THORIUM_EXCLUDE="World of Warcraft"
KEYWORDS_PROTACTINIUM="Protactinium"
KEYWORDS_URANIUM="Uranium"
KEYWORDS_NEPTUNIUM="Neptunium"
KEYWORDS_PLUTONIUM="Plutonium"
KEYWORDS_PLUTONIUM_EXCLUDE="The Sims|Duke Nukem"
KEYWORDS_AMERICIUM="Americium"
KEYWORDS_CURIUM="Curium"
KEYWORDS_BERKELIUM="Berkelium"
KEYWORDS_CALIFORNIUM="Californium"
KEYWORDS_EINSTEINIUM="Einsteinium"
KEYWORDS_FERMIUM="\bFermium"
KEYWORDS_MENDELEVIUM="Mendelevium"
KEYWORDS_NOBELIUM="Nobelium"
KEYWORDS_LAWRENCIUM="Lawrencium"
KEYWORDS_ACTINIDESERIES_ALL="$KEYWORDS_ACTINIUM|$KEYWORDS_AMERICIUM|$KEYWORDS_BERKELIUM|$KEYWORDS_CALIFORNIUM|$KEYWORDS_CURIUM|$KEYWORDS_EINSTEINIUM|$KEYWORDS_FERMIUM|$KEYWORDS_LAWRENCIUM|$KEYWORDS_MENDELEVIUM|$KEYWORDS_NEPTUNIUM|$KEYWORDS_NOBELIUM|$KEYWORDS_PLUTONIUM|$KEYWORDS_PROTACTINIUM|$KEYWORDS_THORIUM|$KEYWORDS_URANIUM"

if [ "$1" == "" ];
then

  debug_start "Actinide series"

  ACTINIUM=$(egrep -i "$KEYWORDS_ACTINIUM" "$NEWPAGES")
  THORIUM=$(egrep -i "$KEYWORDS_THORIUM" "$NEWPAGES" | egrep -iv "$KEYWORDS_THORIUM_EXCLUDE")
  PROTACTINIUM=$(egrep -i "$KEYWORDS_PROTACTINIUM" "$NEWPAGES")
  URANIUM=$(egrep -i "$KEYWORDS_URANIUM" "$NEWPAGES")
  NEPTUNIUM=$(egrep -i "$KEYWORDS_NEPTUNIUM" "$NEWPAGES")
  PLUTONIUM=$(egrep -i "$KEYWORDS_PLUTONIUM" "$NEWPAGES" | egrep -iv "$KEYWORDS_PLUTONIUM_EXCLUDE")
  AMERCIUM=$(egrep -i "$KEYWORDS_AMERICIUM" "$NEWPAGES")
  CURIUM=$(egrep -i "$KEYWORDS_CURIUM" "$NEWPAGES")
  BERKELIUM=$(egrep -i "$KEYWORDS_BERKELIUM" "$NEWPAGES")
  CALIFORNIUM=$(egrep -i "$KEYWORDS_CALIFORNIUM" "$NEWPAGES")
  EINSTEINIUM=$(egrep -i "$KEYWORDS_EINSTEINIUM" "$NEWPAGES")
  FERMIUM=$(egrep -i "$KEYWORDS_FERMIUM" "$NEWPAGES")
  MENDELEVIUM=$(egrep -i "$KEYWORDS_MENDELEVIUM" "$NEWPAGES")
  NOBELIUM=$(egrep -i "$KEYWORDS_NOBELIUM" "$NEWPAGES" )
  LAWRENCIUM=$(egrep -i "$KEYWORDS_LAWRENCIUM" "$NEWPAGES")

  categorize "ACTINIUM" "Actinium"
  categorize "THORIUM" "Thorium"
  categorize "PROTACTINIUM" "Protactinium"
  categorize "URANIUM" "Uranium"
  categorize "NEPTUNIUM" "Neptunium"
  categorize "PLUTONIUM" "Plutonium"
  categorize "AMERCIUM" "Americium"
  categorize "CURIUM" "Curium"
  categorize "BERKELIUM" "Berkelium"
  categorize "CALIFORNIUM" "Californium"
  categorize "EINSTEINIUM" "Einsteinium"
  categorize "FERMIUM" "Fermium"
  categorize "MENDELEVIUM" "Mendelevium"
  categorize "NOBELIUM" "Nobelium"
  categorize "LAWRENCIUM" "Lawrencium"

  debug_end "Actinide series"

fi