#!/bin/bash

./catscripts/Science/Chemistry/Elements/Group1.sh
./catscripts/Science/Chemistry/Elements/Group2.sh
./catscripts/Science/Chemistry/Elements/Group3.sh
./catscripts/Science/Chemistry/Elements/Group4.sh
./catscripts/Science/Chemistry/Elements/Group5.sh
./catscripts/Science/Chemistry/Elements/Group6.sh
./catscripts/Science/Chemistry/Elements/Group7.sh
./catscripts/Science/Chemistry/Elements/Group8.sh
./catscripts/Science/Chemistry/Elements/Group9.sh
./catscripts/Science/Chemistry/Elements/Group10.sh
./catscripts/Science/Chemistry/Elements/Group11.sh
./catscripts/Science/Chemistry/Elements/Group12.sh
./catscripts/Science/Chemistry/Elements/Group13.sh
./catscripts/Science/Chemistry/Elements/Group14.sh
./catscripts/Science/Chemistry/Elements/Group15.sh
./catscripts/Science/Chemistry/Elements/Group16.sh
./catscripts/Science/Chemistry/Elements/Group17.sh
./catscripts/Science/Chemistry/Elements/Group18.sh
./catscripts/Science/Chemistry/Elements/Lanthanides.sh
