#!/bin/bash

KEYWORDS_LANTHANUM="Lanthanum"
KEYWORDS_CERIUM="Cerium"
KEYWORDS_PRASEODYMIUM="Praseodymium"
KEYWORDS_NEODYMIUM="Neodymium"
KEYWORDS_PROMETHIUM="Promethium"
KEYWORDS_SAMARIUM="Samarium"
KEYWORDS_EUROPIUM="Europium"
KEYWORDS_GADOLINIUM="Gadolinium"
KEYWORDS_TERBIUM="\bTerbium"
KEYWORDS_DYSPROSIUM="Dysprosium"
KEYWORDS_HOLMIUM="Holmium"
KEYWORDS_ERBIUM="\bErbium"
KEYWORDS_THULIUM="Thulium"
KEYWORDS_YTTERBIUM="Ytterbium"
KEYWORDS_LUTETIUM="Lutetium"
KEYWORDS_LANTHANIDE_ELEMENTS="$KEYWORDS_LANTHANUM|$KEYWORDS_CERIUM|$KEYWORDS_PRASEODYMIUM|$KEYWORDS_NEODYMIUM|$KEYWORDS_PROMETHIUM|$KEYWORDS_SAMARIUM|$KEYWORDS_EUROPIUM|$KEYWORDS_GADOLINIUM|$KEYWORDS_TERBIUM|$KEYWORDS_DYSPROSIUM|$KEYWORDS_HOLMIUM|$KEYWORDS_ERBIUM|$KEYWORDS_THULIUM|$KEYWORDS_YTTERBIUM|$KEYWORDS_LUTETIUM"

if [ "$1" == "" ];
then

  debug_start "Lanthanide group"

  LANTHANUM=$(egrep -i "$KEYWORDS_LANTHANUM" "$NEWPAGES")
  CERIUM=$(egrep -i "$KEYWORDS_CERIUM" "$NEWPAGES")
  PRASEODYMIUM=$(egrep -i "$KEYWORDS_PRASEODYMIUM" "$NEWPAGES")
  NEODYMIUM=$(egrep -i "$KEYWORDS_NEODYMIUM" "$NEWPAGES")
  PROMETHIUM=$(egrep -i "$KEYWORDS_PROMETHIUM" "$NEWPAGES")
  SAMARIUM=$(egrep -i "$KEYWORDS_SAMARIUM" "$NEWPAGES")
  EUROPIUM=$(egrep -i "$KEYWORDS_EUROPIUM" "$NEWPAGES")
  GADOLINIUM=$(egrep -i "$KEYWORDS_GADOLINIUM" "$NEWPAGES")
  TERBIUM=$(egrep -i "$KEYWORDS_TERBIUM" "$NEWPAGES")
  DYSPROSIUM=$(egrep -i "$KEYWORDS_DYSPROSIUM" "$NEWPAGES")
  HOLMIUM=$(egrep -i "$KEYWORDS_HOLMIUM" "$NEWPAGES")
  ERBIUM=$(egrep -i "$KEYWORDS_ERBIUM" "$NEWPAGES")
  THULIUM=$(egrep -i "$KEYWORDS_THULIUM" "$NEWPAGES")
  YTTERBIUM=$(egrep -i "$KEYWORDS_YTTERBIUM" "$NEWPAGES")
  LUTETIUM=$(egrep -i "$KEYWORDS_LUTETIUM" "$NEWPAGES")

  categorize "LANTHANUM" "Lanthanum"
  categorize "CERIUM" "Cerium"
  categorize "PRASEODYMIUM" "Praseodymium"
  categorize "NEODYMIUM" "Neodymium"
  categorize "PROMETHIUM" "Promethium"
  categorize "SAMARIUM" "Samarium"
  categorize "EUROPIUM" "Europium"
  categorize "GADOLINIUM" "Gadolinium"
  categorize "TERBIUM" "Terbium"
  categorize "DYSPROSIUM" "Dysprosium"
  categorize "HOLMIUM" "Holmium"
  categorize "ERBIUM" "Erbium"
  categorize "THULIUM" "Thulium"
  categorize "YTTERBIUM" "Ytterbium"
  categorize "LUTETIUM" "Lutetium"

  debug_end "Lanthanide group"

fi