#!/bin/bash

KEYWORDS_CALIFORNIA="California|,(| )CA( |$)"
KEYWORDS_LOSANGELES="Los(| )Angeles"
KEYWORDS_SACRAMENTO="Sacramento"
KEYWORDS_SANDIEGO="San(| )Diego"
KEYWORDS_SANFRANCISCO="San(| )Francisco"
KEYWORDS_UCLA="\bUCLA|University(| )of(| )California(|,)(| )Los(| )Angeles"
KEYWORDS_LOSANGELES_EXCLUDE="$KEYWORDS_UCLA"
KEYWORDS_CALIFORNIA_EXCLUDE="$KEYWORDS_LOSANGELES|$KEYWORDS_SACRAMENTO|$KEYWORDS_SANDIEGO|$KEYWORDS_SANFRANCISCO|$KEYWORDS_UCLA"
KEYWORDS_CALIFORNIA_ALL="$KEYWORDS_CALIFORNIA|$KEYWORDS_LOSANGELES|$KEYWORDS_SACRAMENTO|$KEYWORDS_SANDIEGO|$KEYWORDS_UCLA"

if [ "$1" == "" ];
then

  debug_start "California"

  CALIFORNIA=$(egrep -i "$KEYWORDS_CALIFORNIA" "$NEWPAGES" | egrep -iv "$KEYWORDS_CALIFORNIA_EXCLUDE")
  LOSANGELES=$(egrep -i "$KEYWORDS_LOSANGELES" "$NEWPAGES" | egrep -iv "$KEYWORDS_LOSANGELES_EXCLUDE")
  SACRAMENTO=$(egrep -i "$KEYWORDS_SACRAMENTO" "$NEWPAGES")
  SANDIEGO=$(egrep -i "$KEYWORDS_SANDIEGO" "$NEWPAGES")
  SANFRANCISCO=$(egrep -i "$KEYWORDS_SANFRANCISCO" "$NEWPAGES")
  UCLA=$(egrep -i "$KEYWORDS_UCLA" "$NEWPAGES")

  categorize "CALIFORNIA" "California"
  categorize "LOSANGELES" "Los Angeles"
  categorize "SACRAMENTO" "Sacramento"
  categorize "SANDIEGO" "San Diego"
  categorize "SANFRANCISCO" "San Francisco"
  categorize "UCLA" "UCLA"

  debug_end "California"

fi
