#!/bin/bash

KEYWORDS_UNITEDKINGDOM="United(| )Kingdom|\bUK\b|\bU\.K\b"

UNITEDKINGDOMDIR="./catscripts/Government/Countries/United_Kingdom"

if [ "$1" == "" ]; #normal operation
then

  debug_start "United Kingdom"

  . $UNITEDKINGDOMDIR/England/England.sh #KEYWORDS_ENGLAND_ALL
  . $UNITEDKINGDOMDIR/Northern_Ireland/NorthernIreland.sh #KEYWORDS_NORTHERNIRELAND_ALL
  . $UNITEDKINGDOMDIR/Scotland/Scotland.sh #KEYWORDS_SCOTLAND_ALL
  . $UNITEDKINGDOMDIR/Wales/Wales.sh #KEYWORDS_WALES_ALL

  KEYWORDS_UNITEDKINGDOM_EXCLUDE="$KEYWORDS_ENGLAND_ALL|$KEYWORDS_NORTHERNIRELAND_ALL|$KEYWORDS_SCOTLAND_ALL|$KEYWORDS_WALES_ALL"
  KEYWORDS_UNITEDKINGDOM_ALL="$KEYWORDS_UNITEDKINGDOM|$KEYWORDS_UNITEDKINGDOM_EXCLUDE"

  UNITEDKINGDOM=$(egrep -i "$KEYWORDS_UNITEDKINGDOM" "$NEWPAGES" | egrep -iv "$KEYWORDS_UNITEDKINGDOM_EXCLUDE")

  if [ "$UNITEDKINGDOM" != "" ];
  then
    printf "%s" "$UNITEDKINGDOM" > UnitedKingdom.txt
    export CATFILE="UnitedKingdom.txt"
    export CATNAME="United Kingdom"
    $CATEGORIZE
    rm UnitedKingdom.txt
    unset UNITEDKINGDOM
  fi

  debug_end "United Kingdom"

else

  . $UNITEDKINGDOMDIR/England/England.sh norun #KEYWORDS_ENGLAND_ALL
  . $UNITEDKINGDOMDIR/Northern_Ireland/NorthernIreland.sh norun #KEYWORDS_NORTHERNIRELAND_ALL
  . $UNITEDKINGDOMDIR/Scotland/Scotland.sh norun #KEYWORDS_SCOTLAND_ALL
  . $UNITEDKINGDOMDIR/Wales/Wales.sh norun #KEYWORDS_WALES_ALL

  KEYWORDS_UNITEDKINGDOM_EXCLUDE="$KEYWORDS_ENGLAND_ALL|$KEYWORDS_NORTHERNIRELAND_ALL|$KEYWORDS_SCOTLAND_ALL|$KEYWORDS_WALES_ALL"
  KEYWORDS_UNITEDKINGDOM_ALL="$KEYWORDS_UNITEDKINGDOM|$KEYWORDS_UNITEDKINGDOM_EXCLUDE"

fi