#!/bin/bash

KEYWORDS_OLYMPICS="Ol(y|i)mpic"

KEYWORDS_SOCHI2014="$KEYWORDS_OLYMPICS.+sochi|sochi.+$KEYWORDS_OLYMPICS|2014(| )(Winter|)(| )(Games|$KEYWORDS_OLYMPICS)|$KEYWORDS_OLYMPICS.+2014"
KEYWORDS_LONDON2012="$KEYWORDS_OLYMPICS.+london|london.+$KEYWORDS_OLYMPICS|2012(| )(Summer|)(| )(Games|$KEYWORDS_OLYMPICS)|$KEYWORDS_OLYMPICS.+2012"
KEYWORDS_ANCIENTGREEKOLYMPICS="ancient.+$KEYWORDS_OLYMPICS|$KEYWORDS_OLYMPICS.+ancient"

KEYWORDS_OLYMPICS_EXCLUDE="$KEYWORDS_ANCIENTGREEKOLYMPICS|$KEYWORDS_LONDON2012|$KEYWORDS_SOCHI2014"

if [ "$1" == "" ];
then

  debug_start "Olympics"
  
  SOCHI2014=$(egrep -i "$KEYWORDS_SOCHI2014" "$NEWPAGES")

  categorize "SOCHI2014" "2014 Winter Olympics"

  LONDON2012=$(egrep -i "$KEYWORDS_LONDON2012" "$NEWPAGES")

  categorize "LONDON2012" "2012 Summer Olympics"

  ANCIENTGREEKOLYMPICS=$(egrep -i "$KEYWORDS_ANCIENTGREEKOLYMPICS" "$NEWPAGES")

  categorize "ANCIENTGREEKOLYMPICS" "Ancient Greek Olympics"

  OLYMPICS=$(egrep -i "$KEYWORDS_OLYMPICS" "$NEWPAGES" | egrep -iv "$KEYWORDS_OLYMPICS_EXCLUDE")

  categorize "OLYMPICS" "Olympics"

  debug_end "Olympics"

fi